### ISSUE TITLE
Node stuck on block #5667360

### ISSUE THREAD

**Issue by hlolve** [idena-network/idena-go#1138]
Some users reported that after updating to latest node version 1.1.0 or starting sync in new nodes, the process get stuck on previous block number 5667360 (fork11).
Copying idenachain from other nodes that are in sync node works OK and get current block number

**Comment by midenaio** [comment]
@hlolve thanks for bringing this up. Could you share the node log file?

**Comment by hlolve** [comment]
I don´t have previous log, but deleted all and make it again.

INFO [07-11|12:34:41.560] Idena node is starting                   version=1.1.0
INFO [07-11|12:34:41.566] initial HTTP endpoint opened             url=http://localhost:9119 cors=* vhosts=localhost
INFO [07-11|12:34:50.271] Ipfs initialized                         peerId=QmWsQAa3H5wttd8DFeUsvvLNvNPtE5avizKq7kxcgWx2Ug
WARN [07-11|12:34:50.277] cannot parse subscriptions.json          err="unexpected end of JSON input"
INFO [07-11|12:34:50.280] Deferred txs loaded                      cnt=0
INFO [07-11|12:34:50.282] Set new fd limit                         value=1000000
INFO [07-11|12:35:02.548] Chain initialized                        block=0xedf194e0fa8eb510641d4bed7fe06b3b6a88d3e01525e0297e9d79e3be2161fa height=4871137
INFO [07-11|12:35:02.548] Coinbase address                         addr=0x06456192ba97b2dF87cf8d506cb0e2D21E5F4264
INFO [07-11|12:35:03.245] Start consensus protocol                 pubKey=0x0410001a16a960140cb4191afa3d7267a7bf85154313daeee55d644992530ad4c092785d73db3c04d848a4876d27ee1673f724d0cd1ecd13d9b85dfcdce8ad813f
INFO [07-11|12:35:03.246] ipfs gc skipped due to soon validation 
INFO [07-11|12:35:03.246] ipfs gc next time: 2023-07-12 12:35:03.246290033 +0000 UTC 
INFO [07-11|12:35:03.246] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:35:03.258] HTTP endpoint closed                     url=http://localhost:9119
INFO [07-11|12:35:03.261] HTTP endpoint opened                     url=http://localhost:9119 cors=* vhosts=localhost
INFO [07-11|12:35:08.246] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:35:13.248] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:35:14.699] Peer connected                           id=QmSxgjqM4weRuERDfq5sszYsFAiGP8MVV7vTC8GeyxuNzK inbound=true shardId=0
****
INFO [07-11|12:35:18.252] Found manifest                           component=downloader height=5666497
****
INFO [07-11|12:35:18.253] Fast sync will be used                   component=downloader
INFO [07-11|12:35:19.310] Peer connected                           id=Qmdu445VknjWxxicXbfPybFXviSEagtZC5wqN4JxE5LNMM inbound=true shardId=0
INFO [07-11|12:35:19.525] Start process batch                      component=downloader from=4871138 to=4872138
INFO [07-11|12:35:33.537] Finish process batch                     component=downloader from=4871138 to=4872138
INFO [07-11|12:35:33.537] Start process batch                      component=downloader from=4872139 to=4873139
INFO [07-11|12:35:41.689] Finish process batch                     component=downloader from=4872139 to=4873139
INFO [07-11|12:35:41.697] Start process batch                      component=downloader from=4873140 to=4874140
INFO [07-11|12:35:49.740] Finish process batch                     component=downloader from=4873140 to=4874140
INFO [07-11|12:35:49.740] Start process batch                      component=downloader from=4874141 to=4875141
INFO [07-11|12:35:51.236] Peer connected                           id=QmacdVjSSxuv13HziXzxWAdRsiALd79t7NF1N7qHgHwowZ inbound=false shardId=0
INFO [07-11|12:35:56.304] Finish process batch                     component=downloader from=4874141 to=4875141
INFO [07-11|12:35:56.304] Start process batch                      component=downloader from=4875142 to=4876142
INFO [07-11|12:36:03.792] Finish process batch                     component=downloader from=4875142 to=4876142
INFO [07-11|12:36:03.792] Start process batch                      component=downloader from=4876143 to=4877143
INFO [07-11|12:36:11.054] Finish process batch                     component=downloader from=4876143 to=4877143
INFO [07-11|12:36:11.054] Start process batch                      component=downloader from=4877144 to=4878144
INFO [07-11|12:36:20.509] Peer connected                           id=QmXqctaLGoSyPVCBbNrWt9auZ3VnrQXSsZ7awruxky7Zjt inbound=true  shardId=0
INFO [07-11|12:36:20.537] Finish process batch                     component=downloader from=4877144 to=4878144
INFO [07-11|12:36:20.537] Start process batch                      component=downloader from=4878145 to=4879145
INFO [07-11|12:36:23.543] Peer connected                           id=QmcVLtWqbh5gHz1ZZWXw2xj4g7K3LD2NNo4EwXAgk34BeX inbound=false shardId=0
INFO [07-11|12:36:32.777] Finish process batch                     component=downloader from=4878145 to=4879145
INFO [07-11|12:36:32.777] Start process batch                      component=downloader from=4879146 to=4880146
INFO [07-11|12:36:36.058] Peer connected                           id=QmNxvhoqtk7AT8geDQrZVd5mff4pv4i67fJafoENznVTN9 inbound=false shardId=0
INFO [07-11|12:36:41.638] Finish process batch                     component=downloader from=4879146 to=4880146
INFO [07-11|12:36:41.639] Start process batch                      component=downloader from=4880147 to=4881147
INFO [07-11|12:36:48.586] Finish process batch                     component=downloader from=4880147 to=4881147
INFO [07-11|12:36:48.586] Start process batch                      component=downloader from=4881148 to=4882148
INFO [07-11|12:36:55.315] Finish process batch                     component=downloader from=4881148 to=4882148
INFO [07-11|12:36:55.316] Start process batch                      component=downloader from=4882149 to=4883149
INFO [07-11|12:36:58.883] Peer connected                           id=QmX839Ai2MLVbGK7WoZmhpzeXzQQkjY2W9R9AbctNZKKBn inbound=false shardId=0
INFO [07-11|12:37:01.598] Finish process batch                     component=downloader from=4882149 to=4883149
INFO [07-11|12:37:01.598] Start process batch                      component=downloader from=4883150 to=4884150
INFO [07-11|12:37:09.271] Finish process batch                     component=downloader from=4883150 to=4884150
INFO [07-11|12:37:09.272] Start process batch                      component=downloader from=4884151 to=4885151
INFO [07-11|12:37:17.212] Finish process batch                     component=downloader from=4884151 to=4885151
INFO [07-11|12:37:17.212] Start process batch                      component=downloader from=4885152 to=4886152
INFO [07-11|12:37:25.258] Finish process batch                     component=downloader from=4885152 to=4886152
INFO [07-11|12:37:25.259] Start process batch                      component=downloader from=4886153 to=4887153
INFO [07-11|12:37:32.782] Finish process batch                     component=downloader from=4886153 to=4887153
INFO [07-11|12:37:32.783] Start process batch                      component=downloader from=4887154 to=4888154
INFO [07-11|12:37:42.697] Finish process batch                     component=downloader from=4887154 to=4888154
INFO [07-11|12:37:42.697] Start process batch                      component=downloader from=4888155 to=4889155
INFO [07-11|12:37:49.767] Finish process batch                     component=downloader from=4888155 to=4889155
INFO [07-11|12:37:49.767] Start process batch                      component=downloader from=4889156 to=4890156
INFO [07-11|12:37:57.406] Finish process batch                     component=downloader from=4889156 to=4890156
INFO [07-11|12:37:57.407] Start process batch                      component=downloader from=4890157 to=4891157
INFO [07-11|12:38:04.292] Finish process batch                     component=downloader from=4890157 to=4891157
INFO [07-11|12:38:04.294] Start process batch                      component=downloader from=4891158 to=4892158
INFO [07-11|12:38:10.753] Finish process batch                     component=downloader from=4891158 to=4892158
INFO [07-11|12:38:10.753] Start process batch                      component=downloader from=4892159 to=4893159
INFO [07-11|12:38:18.156] Finish process batch                     component=downloader from=4892159 to=4893159
INFO [07-11|12:38:18.158] Start process batch                      component=downloader from=4893160 to=4894160
INFO [07-11|12:38:24.311] Peer connected                           id=QmZ2GihvEUu9Pvzc4pxTeXGtEqwmsLVUcAY3cJpPDTaRSw inbound=false shardId=0
INFO [07-11|12:38:25.267] Finish process batch                     component=downloader from=4893160 to=4894160
INFO [07-11|12:38:25.267] Start process batch                      component=downloader from=4894161 to=4895161
INFO [07-11|12:38:28.551] Peer connected                           id=QmNTCqZJo3y3wvpGhaFpj9bbQeppYVA8JofNLFUwoBWCui inbound=false shardId=0
INFO [07-11|12:38:32.215] Finish process batch                     component=downloader from=4894161 to=4895161
INFO [07-11|12:38:32.222] Start process batch                      component=downloader from=4895162 to=4896162
INFO [07-11|12:38:33.009] no slots for shard, peer will be disconnected peerId=QmXWxsS6siMrRfdLwkfjG7MzKxDWJcbhsuS5PPutfDsiUM shardId=0
INFO [07-11|12:38:39.137] Finish process batch                     component=downloader from=4895162 to=4896162
INFO [07-11|12:38:39.137] Start process batch                      component=downloader from=4896163 to=4897163
INFO [07-11|12:38:46.726] Finish process batch                     component=downloader from=4896163 to=4897163
INFO [07-11|12:38:46.726] Start process batch                      component=downloader from=4897164 to=4898164
INFO [07-11|12:38:50.040] no slots for shard, peer will be disconnected peerId=QmUHFQz6afmJ355DhdBQyLuAexPMvUpsqTE7ewbV8v46QP shardId=0
INFO [07-11|12:38:55.671] Finish process batch                     component=downloader from=4897164 to=4898164
INFO [07-11|12:38:55.671] Start process batch                      component=downloader from=4898165 to=4899165
INFO [07-11|12:39:03.599] no slots for shard, peer will be disconnected peerId=QmSt9MtFa34XRSxa4uF3MJdwtPmgpDaNnkRQmJy85VNJhn shardId=0
INFO [07-11|12:39:04.814] Finish process batch                     component=downloader from=4898165 to=4899165
INFO [07-11|12:39:04.814] Start process batch                      component=downloader from=4899166 to=4900166
INFO [07-11|12:39:11.870] Finish process batch                     component=downloader from=4899166 to=4900166
INFO [07-11|12:39:11.871] Start process batch                      component=downloader from=4900167 to=4901167
INFO [07-11|12:39:18.078] Finish process batch                     component=downloader from=4900167 to=4901167
INFO [07-11|12:39:18.079] Start process batch                      component=downloader from=4901168 to=4902168
INFO [07-11|12:39:27.468] Finish process batch                     component=downloader from=4901168 to=4902168
INFO [07-11|12:39:27.468] Start process batch                      component=downloader from=4902169 to=4903169
INFO [07-11|12:39:34.160] Finish process batch                     component=downloader from=4902169 to=4903169
INFO [07-11|12:39:34.160] Start process batch                      component=downloader from=4903170 to=4904170
INFO [07-11|12:39:40.711] Finish process batch                     component=downloader from=4903170 to=4904170
INFO [07-11|12:39:40.711] Start process batch                      component=downloader from=4904171 to=4905171
INFO [07-11|12:39:47.302] Finish process batch                     component=downloader from=4904171 to=4905171
INFO [07-11|12:39:47.302] Start process batch                      component=downloader from=4905172 to=4906172
INFO [07-11|12:39:50.284] metric since 2023-07-11 12:34:50.280308214 +0000 UTC
 name             bytesSent bytesReceived msgSent msgReceived 
 batchPush        0         678869        0       15680       
 blockRange       0         15796352      0       46          
 getBlockByHash   0         195           0       5           
 getBlocksRange   782       0             46      0           
 handshake        0         734           0       12          
 newTx            0         1290675       0       10449       
 proposeBlock     0         25146         0       41          
 proposeProof     0         8733          0       41          
 pull             670300    0             26812   0           
 snapshotManifest 0         738           0       9           
 vote             0         2447348       0       16267       
 total            671082    20248790      0       0 
INFO [07-11|12:39:54.232] Finish process batch                     component=downloader from=4905172 to=4906172
INFO [07-11|12:39:54.234] Start process batch                      component=downloader from=4906173 to=4907173
INFO [07-11|12:40:01.934] Finish process batch                     component=downloader from=4906173 to=4907173
INFO [07-11|12:40:01.935] Start process batch                      component=downloader from=4907174 to=4908174
INFO [07-11|12:40:04.262] Peer disconnected                        id=QmX839Ai2MLVbGK7WoZmhpzeXzQQkjY2W9R9AbctNZKKBn shardId=0
INFO [07-11|12:40:09.166] Finish process batch                     component=downloader from=4907174 to=4908174
INFO [07-11|12:40:09.167] Start process batch                      component=downloader from=4908175 to=4909175
INFO [07-11|12:40:12.313] Peer connected                           id=QmNpghXWRpYdCkHe7o62snnLKVDn6iJBwHLkFimfGzS7y3 inbound=false shardId=0
INFO [07-11|12:40:12.780] no slots for shard, peer will be disconnected peerId=QmUHFQz6afmJ355DhdBQyLuAexPMvUpsqTE7ewbV8v46QP shardId=0
INFO [07-11|12:40:15.932] Finish process batch                     component=downloader from=4908175 to=4909175
INFO [07-11|12:40:15.932] Start process batch                      component=downloader from=4909176 to=4910176
INFO [07-11|12:40:22.488] Finish process batch                     component=downloader from=4909176 to=4910176
INFO [07-11|12:40:22.488] Start process batch                      component=downloader from=4910177 to=4911177
INFO [07-11|12:40:27.986] Peer connected                           id=QmeXFzy7zejZfXwQucaAbH9n3uHgGxvFYkwvjERFed3vRX inbound=true  shardId=0
INFO [07-11|12:40:31.516] Finish process batch                     component=downloader from=4910177 to=4911177
INFO [07-11|12:40:31.518] Start process batch                      component=downloader from=4911178 to=4912178
INFO [07-11|12:40:43.510] Finish process batch                     component=downloader from=4911178 to=4912178
INFO [07-11|12:40:43.511] Start process batch                      component=downloader from=4912179 to=4913179
INFO [07-11|12:40:50.564] Finish process batch                     component=downloader from=4912179 to=4913179
INFO [07-11|12:40:50.564] Start process batch                      component=downloader from=4913180 to=4914180
INFO [07-11|12:40:57.222] no slots for shard, peer will be disconnected peerId=QmZZV7tAd24x8amNSYsMSD24Xt9AKmGKErpxKWA5zJWKtK shardId=0
INFO [07-11|12:40:57.610] Finish process batch                     component=downloader from=4913180 to=4914180
INFO [07-11|12:40:57.611] Start process batch                      component=downloader from=4914181 to=4915181
INFO [07-11|12:41:04.030] Peer connected                           id=QmbCbp9Wn44tHdgPzRYuhh3yTd7PqRqVJjTSnCfkPNwP9w inbound=true  shardId=0
INFO [07-11|12:41:07.999] Finish process batch                     component=downloader from=4914181 to=4915181
INFO [07-11|12:41:08.002] Start process batch                      component=downloader from=4915182 to=4916182
INFO [07-11|12:41:18.553] no slots for shard, peer will be disconnected peerId=QmdBP1RaZs6JgiZummpLhGyHidGSrTddkKs8XWYgTtzCN7 shardId=0
INFO [07-11|12:41:18.613] no slots for shard, peer will be disconnected peerId=Qmc1ckQ1poFrUr9KQ1iEvjrud1sNRmB4PcqinmQ14Y5rss shardId=0
INFO [07-11|12:41:24.106] Finish process batch                     component=downloader from=4915182 to=4916182
INFO [07-11|12:41:24.106] Start process batch                      component=downloader from=4916183 to=4917183
INFO [07-11|12:41:32.384] Finish process batch                     component=downloader from=4916183 to=4917183
INFO [07-11|12:41:32.384] Start process batch                      component=downloader from=4917184 to=4918184
INFO [07-11|12:41:39.604] Finish process batch                     component=downloader from=4917184 to=4918184
INFO [07-11|12:41:39.606] Start process batch                      component=downloader from=4918185 to=4919185
INFO [07-11|12:42:06.966] Peer aborts connection                   id=QmeXFzy7zejZfXwQucaAbH9n3uHgGxvFYkwvjERFed3vRX shardId=0 reason="peer was selected to disconnect while renewing peers"
INFO [07-11|12:42:08.422] Finish process batch                     component=downloader from=4918185 to=4919185
INFO [07-11|12:42:08.422] Start process batch                      component=downloader from=4919186 to=4920186
INFO [07-11|12:42:21.765] no slots for shard, peer will be disconnected peerId=QmQPd3drSiAS4AWV3hGLQyyR2qcEVjYXu8NHyVeyZ1uc84 shardId=0
INFO [07-11|12:42:33.560] Peer connected                           id=QmcqiBNaWUAKuyaLa9ZQqR3rp44n4W3rHQb6yov8HxZwpr inbound=true  shardId=0
INFO [07-11|12:42:37.304] Finish process batch                     component=downloader from=4919186 to=4920186
INFO [07-11|12:42:37.305] Start process batch                      component=downloader from=4920187 to=4921187
INFO [07-11|12:42:45.555] Finish process batch                     component=downloader from=4920187 to=4921187
INFO [07-11|12:42:45.555] Start process batch                      component=downloader from=4921188 to=4922188
INFO [07-11|12:42:58.861] Finish process batch                     component=downloader from=4921188 to=4922188
INFO [07-11|12:42:58.861] Start process batch                      component=downloader from=4922189 to=4923189
INFO [07-11|12:43:24.906] Finish process batch                     component=downloader from=4922189 to=4923189
INFO [07-11|12:43:24.907] Start process batch                      component=downloader from=4923190 to=4924190
INFO [07-11|12:43:58.664] no slots for shard, peer will be disconnected peerId=QmYxQ1Zhe48QgQrZg8y4nRqpY7BHYeTi47yW6TxofkhigM shardId=0
INFO [07-11|12:44:01.490] Peer connected                           id=Qmd2DxS8E7c8eLeJWYCRyE1cdTTrPHCYCr8knwpg4TS8gT inbound=true  shardId=0
INFO [07-11|12:44:04.909] Finish process batch                     component=downloader from=4923190 to=4924190
INFO [07-11|12:44:04.909] Start process batch                      component=downloader from=4924191 to=4925191
INFO [07-11|12:44:19.364] Finish process batch                     component=downloader from=4924191 to=4925191
INFO [07-11|12:44:19.377] Start process batch                      component=downloader from=4925192 to=4926192
INFO [07-11|12:44:36.295] Finish process batch                     component=downloader from=4925192 to=4926192
INFO [07-11|12:44:36.296] Start process batch                      component=downloader from=4926193 to=4927193
INFO [07-11|12:44:43.475] no slots for shard, peer will be disconnected peerId=QmatvE7zyz6Ty2bCXbcrGW8VamTyqtHteQzGVhQyNUqTiy shardId=0
INFO [07-11|12:44:44.729] Finish process batch                     component=downloader from=4926193 to=4927193
INFO [07-11|12:44:44.731] Start process batch                      component=downloader from=4927194 to=4928194
INFO [07-11|12:44:50.303] metric since 2023-07-11 12:34:50.280308214 +0000 UTC
 name             bytesSent bytesReceived msgSent msgReceived 
 batchPush        0         1770748       0       51212       
 blockRange       0         25962752      0       68          
 getBlockByHash   0         507           0       13          
 getBlocksRange   1156      0             68      0           
 handshake        0         1466          0       24          
 newTx            0         1291665       0       10457       
 proposeBlock     0         121368        0       199         
 proposeProof     0         40896         0       192         
 pull             1621550   0             64862   0           
 snapshotManifest 0         1148          0       14          
 vote             0         8123839       0       53989       
 total            1622706   37314448      0       0 
INFO [07-11|12:44:50.664] Finish process batch                     component=downloader from=4927194 to=4928194
INFO [07-11|12:44:50.665] Start process batch                      component=downloader from=4928195 to=4929195
INFO [07-11|12:44:55.428] Peer aborts connection                   id=Qmdu445VknjWxxicXbfPybFXviSEagtZC5wqN4JxE5LNMM shardId=0 reason="peer was selected to disconnect while renewing peers"
INFO [07-11|12:44:57.088] Finish process batch                     component=downloader from=4928195 to=4929195
INFO [07-11|12:44:57.088] Start process batch                      component=downloader from=4929196 to=4930196
INFO [07-11|12:45:00.707] Peer aborts connection                   id=QmSxgjqM4weRuERDfq5sszYsFAiGP8MVV7vTC8GeyxuNzK shardId=0 reason="peer was selected to disconnect while renewing peers"
INFO [07-11|12:45:04.263] Peer disconnected                        id=QmZ2GihvEUu9Pvzc4pxTeXGtEqwmsLVUcAY3cJpPDTaRSw shardId=0
INFO [07-11|12:45:04.667] Finish process batch                     component=downloader from=4929196 to=4930196
INFO [07-11|12:45:04.668] Start process batch                      component=downloader from=4930197 to=4931197
INFO [07-11|12:45:04.669] All blocks were requested. Wait for applying of blocks component=downloader
INFO [07-11|12:45:10.597] Finish process batch                     component=downloader from=4930197 to=4931197
INFO [07-11|12:45:10.598] Start process batch                      component=downloader from=4931198 to=4932198
INFO [07-11|12:45:53.938] Idena node is starting                   version=1.1.0
INFO [07-11|12:45:53.956] initial HTTP endpoint opened             url=http://localhost:9119 cors=* vhosts=localhost
INFO [07-11|12:45:55.011] Start compacting DB 
INFO [07-11|12:45:55.783] DB compacted                             d=1.790862259s
INFO [07-11|12:46:01.498] Ipfs initialized                         peerId=QmWsQAa3H5wttd8DFeUsvvLNvNPtE5avizKq7kxcgWx2Ug
WARN [07-11|12:46:01.517] cannot parse subscriptions.json          err="unexpected end of JSON input"
INFO [07-11|12:46:01.522] Deferred txs loaded                      cnt=0
INFO [07-11|12:46:01.525] Set new fd limit                         value=1000000
INFO [07-11|12:46:01.529] Chain initialized                        block=0xedf194e0fa8eb510641d4bed7fe06b3b6a88d3e01525e0297e9d79e3be2161fa height=4871137
INFO [07-11|12:46:01.530] Coinbase address                         addr=0x06456192ba97b2dF87cf8d506cb0e2D21E5F4264
INFO [07-11|12:46:02.296] Start consensus protocol                 pubKey=0x0410001a16a960140cb4191afa3d7267a7bf85154313daeee55d644992530ad4c092785d73db3c04d848a4876d27ee1673f724d0cd1ecd13d9b85dfcdce8ad813f
INFO [07-11|12:46:02.300] HTTP endpoint closed                     url=http://localhost:9119
INFO [07-11|12:46:02.302] HTTP endpoint opened                     url=http://localhost:9119 cors=* vhosts=localhost
INFO [07-11|12:46:02.303] ipfs gc skipped due to soon validation 
INFO [07-11|12:46:02.303] ipfs gc next time: 2023-07-12 12:46:02.303361013 +0000 UTC 
INFO [07-11|12:46:02.303] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:46:07.303] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:46:12.305] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:46:17.306] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|12:46:22.257] Peer connected                           id=QmTVvzKm3ZwtASYd7M8cvQsoh3PyU2juj5afugHNdr6TAA inbound=true shardId=0
INFO [07-11|12:46:22.307] Wait for snapshot manifests              component=downloader
****
INFO [07-11|12:46:24.313] Found manifest                           component=downloader height=6237497
****
INFO [07-11|12:46:24.330] Fast sync will be used                   component=downloader
INFO [07-11|12:46:24.954] Start process batch                      component=downloader from=4932001 to=4933001
INFO [07-11|12:46:28.615] Peer connected                           id=QmPsCint4eRVTFMbE2n6ZbEE33WM5B98rqskehKf2wYTJw inbound=true shardId=0
WARN [07-11|12:46:37.149] Flip Tx is not valid                     hash=0x567d28212f6796fc61ba56410f97060d2f21767d6c2981565a86e82e49d11228 err="user is not a candidate"
ERROR[07-11|12:46:37.149] invalid flip                             err="user is not a candidate"
INFO [07-11|12:46:47.527] Finish process batch                     component=downloader from=4932001 to=4933001
INFO [07-11|12:46:47.527] Start process batch                      component=downloader from=4933002 to=4934002
INFO [07-11|12:46:55.173] Peer disconnected                        id=QmTVvzKm3ZwtASYd7M8cvQsoh3PyU2juj5afugHNdr6TAA shardId=0
INFO [07-11|12:46:56.829] Finish process batch                     component=downloader from=4933002 to=4934002
INFO [07-11|12:46:56.831] All blocks were requested. Wait for applying of blocks component=downloader
INFO [07-11|12:46:56.832] Start process batch                      component=downloader from=4934003 to=4935003
INFO [07-11|12:47:14.183] Finish process batch                     component=downloader from=4934003 to=4935003
INFO [07-11|12:47:14.184] Start process batch                      component=downloader from=4935004 to=4936004
INFO [07-11|12:47:21.432] Finish process batch                     component=downloader from=4935004 to=4936004
INFO [07-11|12:47:21.434] Start process batch                      component=downloader from=4936005 to=4937005
INFO [07-11|12:47:22.730] Peer connected                           id=QmcBvNT6NqeyL5vhmhJFo3dvM5cYuRbVLNyR9tt9kGAkoe inbound=false shardId=0
INFO [07-11|12:47:37.157] Peer connected                           id=QmVCwsV8wq8McjKfSuXexWmGg4B8HPNngRuUKtbrEdrCLu inbound=false shardId=0
INFO [07-11|12:47:40.154] Finish process batch                     component=downloader from=4936005 to=4937005
INFO [07-11|12:47:40.154] Start process batch                      component=downloader from=4937006 to=4938006

**Comment by hlolve** [comment]
This is the start with the node deleted

INFO [07-11|12:35:18.252] Found manifest component=downloader height=5666497

If during sync I stop and after restart manifest is to current

INFO [07-11|12:46:24.313] Found manifest component=downloader height=6237497

But if you don´t do this stop and restart previous to reach block 5667360 the node got stuck

**Comment by hlolve** [comment]
![Captura desde 2023-07-11 09-44-28](https://github.com/idena-network/idena-go/assets/83220758/e9b308d1-7a09-48f6-b222-11a01a91cf94)

**Comment by hlolve** [comment]
![Captura desde 2023-07-11 09-47-30](https://github.com/idena-network/idena-go/assets/83220758/a9fc66e3-1c8b-4ee7-b22d-7ba0653a5460)

**Comment by hlolve** [comment]
Maybe the problem is a bootnode with wrong manifest file ?

**Comment by hlolve** [comment]
![3](https://github.com/idena-network/idena-go/assets/83220758/2027acf4-eb6b-4616-9d31-086e49601b2c)

From a user that was updating node previous to last validation day

**Comment by hlolve** [comment]
![4](https://github.com/idena-network/idena-go/assets/83220758/2bfb0973-9b27-4f03-b4b5-385eac9e7b46)

**Comment by hlolve** [comment]
New test, seems some peers are stuck, and send old manifest

INFO [07-11|17:27:24.401] Idena node is starting                   version=1.1.0
INFO [07-11|17:27:24.402] initial HTTP endpoint opened             url=http://localhost:9009 cors=* vhosts=localhost
INFO [07-11|17:27:29.675] Ipfs initialized                         peerId=QmUj9z4dCeUtvDaNxHKFvz2GvJrpjumR1tJJZnxujUspvy
WARN [07-11|17:27:29.683] cannot parse subscriptions.json          err="unexpected end of JSON input"
INFO [07-11|17:27:29.686] Deferred txs loaded                      cnt=0
INFO [07-11|17:27:29.687] Set new fd limit                         value=1000000
INFO [07-11|17:27:40.950] Chain initialized                        block=0xedf194e0fa8eb510641d4bed7fe06b3b6a88d3e01525e0297e9d79e3be2161fa height=4871137
INFO [07-11|17:27:40.950] Coinbase address                         addr=0xf74F1973Ce60fE991fa9D400b96395334c752455
INFO [07-11|17:27:41.617] Start consensus protocol                 pubKey=0x0437ae2e83d865b4b06db2486558aeb0f185d3c5aa7d40e742409feb6ec10899f7fc80294b9187488a31656984835386a446fa91405933b162f5ea38c868fed098
INFO [07-11|17:27:41.617] ipfs gc skipped due to soon validation 
INFO [07-11|17:27:41.617] ipfs gc next time: 2023-07-12 17:27:41.617510387 +0000 UTC 
INFO [07-11|17:27:41.618] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:27:41.617] HTTP endpoint closed                     url=http://localhost:9009
INFO [07-11|17:27:41.620] HTTP endpoint opened                     url=http://localhost:9009 cors=* vhosts=localhost
INFO [07-11|17:27:46.619] Peers are not found. Assume node is synchronized component=downloader
****
INFO [07-11|17:27:50.029] Peer connected                           id=QmSxgjqM4weRuERDfq5sszYsFAiGP8MVV7vTC8GeyxuNzK inbound=true shardId=0
INFO [07-11|17:27:51.620] Found manifest                           component=downloader height=5666497
****
INFO [07-11|17:27:51.620] Fast sync will be used                   component=downloader
INFO [07-11|17:27:52.033] Peer connected                           id=QmcqiBNaWUAKuyaLa9ZQqR3rp44n4W3rHQb6yov8HxZwpr inbound=true shardId=0
INFO [07-11|17:27:52.850] Start process batch                      component=downloader from=4871138 to=4872138
INFO [07-11|17:29:25.010] Idena node is starting                   version=1.1.0
INFO [07-11|17:29:25.012] initial HTTP endpoint opened             url=http://localhost:9009 cors=* vhosts=localhost
INFO [07-11|17:29:26.064] Start compacting DB 
INFO [07-11|17:29:26.140] DB compacted                             d=1.07566659s
INFO [07-11|17:29:28.224] Ipfs initialized                         peerId=QmUj9z4dCeUtvDaNxHKFvz2GvJrpjumR1tJJZnxujUspvy
WARN [07-11|17:29:28.228] cannot parse subscriptions.json          err="unexpected end of JSON input"
INFO [07-11|17:29:28.231] Deferred txs loaded                      cnt=0
INFO [07-11|17:29:28.232] Set new fd limit                         value=1000000
INFO [07-11|17:29:28.236] Chain initialized                        block=0xedf194e0fa8eb510641d4bed7fe06b3b6a88d3e01525e0297e9d79e3be2161fa height=4871137
INFO [07-11|17:29:28.236] Coinbase address                         addr=0xf74F1973Ce60fE991fa9D400b96395334c752455
INFO [07-11|17:29:29.054] Start consensus protocol                 pubKey=0x0437ae2e83d865b4b06db2486558aeb0f185d3c5aa7d40e742409feb6ec10899f7fc80294b9187488a31656984835386a446fa91405933b162f5ea38c868fed098
INFO [07-11|17:29:29.055] ipfs gc skipped due to soon validation 
INFO [07-11|17:29:29.055] ipfs gc next time: 2023-07-12 17:29:29.055026849 +0000 UTC 
INFO [07-11|17:29:29.055] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:29:29.055] HTTP endpoint closed                     url=http://localhost:9009
INFO [07-11|17:29:29.058] HTTP endpoint opened                     url=http://localhost:9009 cors=* vhosts=localhost
INFO [07-11|17:29:34.056] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:29:39.057] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:29:44.057] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:29:49.058] Peers are not found. Assume node is synchronized component=downloader
INFO [07-11|17:29:54.060] Peers are not found. Assume node is synchronized component=downloader
****
INFO [07-11|17:29:58.502] Peer connected                           id=QmUHFQz6afmJ355DhdBQyLuAexPMvUpsqTE7ewbV8v46QP inbound=true shardId=0
INFO [07-11|17:29:59.060] Found manifest                           component=downloader height=6243497
****
INFO [07-11|17:29:59.064] Fast sync will be used                   component=downloader
INFO [07-11|17:29:59.774] Start process batch                      component=downloader from=4871701 to=4872701

**Comment by hlolve** [comment]
Always that node get this peer as first the manifest is wrong

Peer connected id=QmSxgjqM4weRuERDfq5sszYsFAiGP8MVV7vTC8GeyxuNzK

**Comment by RelightMotion** [comment]
Same problem, had several people complaining about it

**Comment by hlolve** [comment]
The problem with node stuck will be present until bad peer leave network or banned by a change in code

**Comment by ltraveler** [comment]
**The daily updated Idena blockchain snapshot could be taken from here:**
https://github.com/ltraveler/idenachain.db

**Comment by ubiubi18** [comment]
Bad peer still didn't left the network, right? Issue seems still persistent
