### ISSUE TITLE
Node stops

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#232]
Who is Travis?
I'm running Client(0.1.4) with built in Node(0.15.0) on Win10 Pro 64bit. Mining is on.
Windows updates are paused for next 35 days, no restarts. No sleep is set.
Node stoped for some reason and I need to click on a button to restart the node.
Is there way to setup autorestart of node?

Here are node logs, hope this is usefull:
[output.zip](https://github.com/idena-network/idena-go/files/3998566/output.zip)

**Comment by rioda-org** [comment]
Node maybe stops when it losess all peers

**Comment by ridenaio** [comment]
This can happen when node panics for some reason. 

This issue is more related to [Idena desktop app](https://github.com/idena-network/idena-desktop). An ability to automatically restart the built-in node will be added soon in the desktop application.
