### ISSUE TITLE
is this project GPL?

### ISSUE THREAD

**Issue by nur-azhar** [idena-network/idena-go#320]

**Comment by csculley** [comment]
I'm also interested in this, as well.

Adding a license will help with encouraging contributions, letting contributors know how their work will be distributed, as well as clarifying the process for redistributions (such as [mine on Arch Linux's AUR](https://aur.archlinux.org/packages/idena-go-git/), which just attempts to build from master).

Thanks!

**Comment by ridenaio** [comment]
Hi, thanks for reaching out.

Yes, we have added the GPL v3 license.
