### ISSUE TITLE
Error 'tx with same hash already exists'

### ISSUE THREAD

**Issue by Endogen** [idena-network/idena-go#336]
While spamming with `SendTx` transactions to test the network i found that i quite often ran into this error. it for example happened at the first try after 514  sent transactions.
![image](https://user-images.githubusercontent.com/226475/78018524-56418800-734e-11ea-9ab1-1cf8f169fa28.png)

i guess this is because i've send the same data over and over pretty fast but i have the feeling that this could also happen to a regular transaction which would be unfortunate.

could this be an issue once the network grows in size?

**Comment by ridenaio** [comment]
Hi, this situation can arise if you send transactions fast. Node has in-memory nonce cache, which is used when you send transactions with zero nonces. This cache is updated only when the transaction is inserted in memory pool. So, if you do not increase nonce by yourself and send two transactions simultaneously, there is a chance that both transactions will have the same nonce.

**Comment by Endogen** [comment]
Ah ok, makes sense. I didn't set the nonce so it is as you described it. Will close it then. Thank you for looking into this.
