### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by dragos9326** [idena-network/idena-go#337]
I got this flip during short validation:
https://scan.idena.io/flip?flip=bafkreihi4md4zwprkwqo2hdqwewxo5acekzsrlk7khxvggff2ld5no3e4e

It is marked as reported, but It still counted on my short session.

Even though the flip is marked as reported, it has strong consensus on right. Is this the right behaviour?

**Comment by ridenaio** [comment]
Hi, thanks for the request.

Flip consensus and flip reporting are different things. If flip is reported, the author does not receive a reward. However, even if flip is reported, it might have strong/weak consensus and it will be counted in validation results.

**Comment by dragos9326** [comment]
Hi,

I think the correct way is to discard reported flips The reports and votes should be correlated to decide if a flip should be used or not. For this example the majority of people thought this flip should be reported(it has 8 reports and 7 votes for right to get strong consensus), but it still counted on validation, which means the majority didn't decide. If we keep the same proportion(I know statistically it doesn't work like that) there are more chances a human who gets this flip on validation would think that it makes no sense and just choose random a side because it has to(this was my case). So I think when calculating consensus, the reports should count to avoid situations like this which I don't think are right.
Take it as a suggestion for next releases.

**Comment by midenaio** [comment]
Please check the latest [#0041 epoch validation results](https://scan.idena.io/validation?epoch=41).

There are 176 flips having no consensus. These nonsense flips were not counted for the short session. In addition there are 106 flips having weak consensus. These flips are also hard to solve, however the person gets 0.5 even for the wrong answer. Consensus does a good job by disqualifying nonsense flips. 

In contrast there are only 35 flips reported. These flips are breaking some rules (e.g. having inappropriate content, etc). The report flip function is introduced in order to make people follow the rules but not for the nonsense flips discovery.

**Comment by dragos9326** [comment]
Hi,

"The report flip function is introduced in order to make people follow the rules but not for the nonsense flips discovery." What I'm saying is that it should be used for the nonsense flips discovery. Because right now through reporting you find a bad flip, but this flip is still used on the short session if it somehow got consensus. So there are people who get a bad flip (makes no sense, writing, doesn't follow the rules, etc) in the short session. This is the image of the flip I'm talking about.
![image](https://user-images.githubusercontent.com/27893340/78232115-77d07a00-74dc-11ea-83df-71b4d3c22ad0.png)

Probably 7/9 people choosing the right side is purely a coincidence because the flip makes no sense. You can't even read the tweets. Also these 7 people who chose the right side + another one out of 9 people committee(so 8/9) reported this as being a bad flip.
I know the chances for a bad flip to get consensus are not great, but it happens. For an user POV the short session should be filled with only valid flips who follow the rules.  If an user receives 6 reported flips who makes no sense he would chose randomly and there is a chance he will fail validation.

I know this is a corner case, but it should be fixed somehow.

**Comment by midenaio** [comment]
https://scan.idena.io/flip?flip=bafkreihi4md4zwprkwqo2hdqwewxo5acekzsrlk7khxvggff2ld5no3e4e

![image](https://user-images.githubusercontent.com/47352542/78236090-fd5f2480-74f2-11ea-8d9a-11562d7b27a5.png)

The text was readable. There is a consensus because of the tweets ordered by date.

**Comment by dragos9326** [comment]
When opened in the app you couldn't see it clearly and pressed by the time you couldn't waste much to try to figure it out the date. This is the first thing I did, but it was too unclear. Maybe you have a dev mode and you can replicate.

Irregardless of this particular flip, the issue still exists: reported flip could count in short validation. Which defeats the purpose to me since the majority of the people marked this flip as bad.

**Comment by midenaio** [comment]
Did you use zooming function during the short validation?

**Comment by dragos9326** [comment]
I didn't know about this function. Anyways, let's forget about this flip. I got 5/6 and got validated. It's ok, although I would've liked to keep my 100%.

Let's focus on the underlined problem. Do you agree with me that a flip that the majority of people("strong consensus" in this case - 8/9 reported) thought it is not good should not count in short validation?

My idea is that if I report a flip, my answer won't matter, because I clearly think that it is not a good flip.

In long validation I could see a flip which makes sense, but it is not related to the words. I report it. This is the right behaviour, right? And the writer doesn't get a reward. But since the flip made sense, I chose the good side in the first round of choosing in long validation. I cannot deselect my option now in the Idena app, I can only change it. Hence even if in the first round of choosing in long validation I choose a side, in the second round I report this flip. If the majority does this, the flip gets consensus, but is also reported. The writer doesn't get a reward and the people who got this in the short validation will choose the consented side most probably. Everything fine in this case. But this seems the only case where reported and consensus work together.

What if I report a flip for not making any sense? or because doesn't follow the rules? How do you differentiate between the reasons it got reported?

My answer should be discarded if I reported the question.
Also deselect should be allowed in the Idena app on validation.
