### ISSUE TITLE
Feature Request: Notify on balance change

### ISSUE THREAD

**Issue by Endogen** [idena-network/idena-go#338]
Add the possibility to notify the user if his balance changed. Basically scanning for new `SendTx` transactions.

**Comment by ridenaio** [comment]
Hi, thanks for the request.

Basically, balance can be changed not only with `SendTx` transactions. Can you please describe a bit more about how you think it should work. Currently, the node does not have any socket interface, only `JSON RPC` is available. For example, now you can poll `dna_getBalance` to identify if the balance has changed.

**Comment by Endogen** [comment]
Sorry, this is not the right place for this request. Will move it over to the client.
