### ISSUE TITLE
Change invite system to not generate invites but directly activate addresses

### ISSUE THREAD

**Issue by Endogen** [idena-network/idena-go#341]
Generated invites can be, and are being, sold. To prevent this as much as possible, the whole invite generation process could be discarded. Leaving only the possibility in client to activate a node address.

The user that wants to be invited, tells the user that invites, only his node address. The user that invites inputs that address into his client and activates the identity of the user that wants to be invited.

That way it's more likely that a new user is already running a node and will not simply waste an invite and you can't sell an invite because you could only sell the nodekey and that does not make any sense since the seller of course knows it.

**Comment by midenaio** [comment]
The issue should be addressed to the Idena client. Idena node allows invitation issuance for the specified address. The function is not yet supported in Idena client.

**Comment by Endogen** [comment]
Should i move this issue to the client?

**Comment by midenaio** [comment]
Yes please

**Comment by Endogen** [comment]
Moved to client: https://github.com/idena-network/idena-desktop/issues/233
