### ISSUE TITLE
Troubles connecting to a remote node

### ISSUE THREAD

**Issue by eppemela** [idena-network/idena-go#357]
Hi there, I’m having trouble connecting the MacOS client to a remote node. Seems like the remote node only accepts locals connections, even though I’ve prepared the config.json file as such:

`{ "IpfsConf": { "Profile": "server" } }`

I’m using a VPN, I can ping the "remote" node so I’m sure that networking is fine. 
I can also telnet from the Mac to a test port open with netcat. 
I can’t telnet to the 9009 port though nor the mac os client can. Am I missing something ?

**Comment by rioda-org** [comment]
When you run node with default settings it listens on http://localhost:9009.
Try to run node with parametar --rpcaddress (your remote server IP)
For unable to telnet to the 9009, dunno, maybe your VPN does not tunnel 9009 port for some reason.
You can also change that with --rpcport (some port you know that works)
Then you can enter in client http://192.168.75.22:8181

**Comment by eppemela** [comment]
Thanks for answering, I'm running the node inside a docker container. I've modified the config.json as follows:

```
{
  "RPC": {
    "HTTPHost": "10.0.3.2",
    "HTTPPort": 9999
  },
  "IpfsConf": {
    "Profile": "server"
  },
  "Sync": {
    "FastSync": true
  }
}
```

but, when I see the logs doesn't seem to work anyhow: 

`HTTP endpoint opened url=http://localhost:9009 cors=* vhosts=localhost`

Any idea how to fix this?

**Comment by rioda-org** [comment]
Oh yeah, I'm not sure at all how to configure all parameters using config.json so I go about and run node with a bunch of arguments.
Try running it like this:
idena --rpcaddress 10.0.3.2 --rpcport 9999

Most of us run node on hosted vps, we run it with default settings, so localhost and 9009. Then we ssh and make tunnel using port 9999 wich tunnels to port 9009. (9999:localhost:9009)
So in client we point to localhost:9999 but node is serving up on localhost:9009

**Comment by eppemela** [comment]
Hi there, I managed to make it work, it was an error on my configuration due to a misleading param on the README file. 
At line 41 I just copied the `--config=<config file name>` and therefore I was running my node with this command line: `idena --config=datadir/config.json`. 

Seemed like my configuration file got totally ignored so I tried changing my docker container to run with: 

`idena --config /home/datadir/config.json` 

As you can see I've used the absolute path to be sure and, most importantly, I've removed the 
**=**. Now my config file gets processed and I can connect to my node with my mac desktop client. 

Awesome! 

Thanks again for your support, I'll close this issue.
