### ISSUE TITLE
insufficient funds error when a tx is injected using dna_sendRawTx endpoint

### ISSUE THREAD

**Issue by menxit** [idena-network/idena-go#359]
Hi, I'm trying to inject a signed tx using the `dna_sendRawTx` endpoint but an "insufficient funds" error is raised (even if there are sufficient funds).

### 1. First of all I retrieve the nonce of my address:
```
{
	"method": "dna_getBalance",
	"id": 2,
	"params": ["0xfE3F5744116B71C9b61Af772C6535A1829d7f2Ac"]
}
```
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "result": {
        "stake": "0",
        "balance": "0.8799999999999046",
        "nonce": 9
    }
}
```

### 2. Then I forge tx:
```
{
	"method": "bcn_getRawTx",
	"id": 2,
	"params": [{
	    "nonce": 10,
	    "epoch": 41,
	    "type": 0,
	    "to": "0xCF979F9472e38d45C577394747a3028ea7433Bb5",
	    "amount": 0.01,
	    "maxFee": 0.000000000000021,
	    "tips": 0,
	    "payload": "0x"
	}]
}
```
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "result": "0xe60a298094cf979f9472e38d45c577394747a3028ea7433bb5872386f26fc10000825208808080"
}
```

### 3. Then I sign the tx:
```
{
	"method": "dna_sign",
	"id": 2,
	"params": ["0xe60a298094cf979f9472e38d45c577394747a3028ea7433bb5872386f26fc10000825208808080"]
}
```
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "result": "0x4b65694247b2519c4c897d94adbeb7309ecc34efd1844c91d086ab9e1de60ef7764464c5e3f8ee234625811a577aa1aa2802789fc1afada8ae2d644a75f822f700"
}
```

### 4. Concatenate forged tx and signature
I'm using javascript for this purpose and the RLP module.
```
const RLP = require("rlp");
const format0x = (buffer: Buffer) => "0x" + buffer.toString("hex");
const forgeSignedTx = data => RLP.encode([
            data.nonce,
            data.epoch,
            data.type,
            data.to,
            data.amount*10**18,
            data.maxFee*10**18,
            data.tips*10**18,
            data.payload || "0x",
            data.signature || "0x",
]);
console.log(format0x(forgeSignedTx));
```
```
0xf8680a298094cf979f9472e38d45c577394747a3028ea7433bb5872386f26fc100008252088080b8414b65694247b2519c4c897d94adbeb7309ecc34efd1844c91d086ab9e1de60ef7764464c5e3f8ee234625811a577aa1aa2802789fc1afada8ae2d644a75f822f700
```

### 5. Inject signed tx
```
{
	"method": "bcn_sendRawTx",
	"id": 2,
	"params": ["0xf8680a298094cf979f9472e38d45c577394747a3028ea7433bb5872386f26fc100008252088080b8414b65694247b2519c4c897d94adbeb7309ecc34efd1844c91d086ab9e1de60ef7764464c5e3f8ee234625811a577aa1aa2802789fc1afada8ae2d644a75f822f700"]
}
```
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32000,
        "message": "insufficient funds"
    }
}
```

p.s. I know that I can use the `dna_sendTransaction` endpoint, but I'd like to be able to inject an offline  forged and signed tx.

**Comment by ridenaio** [comment]
Hi, thanks for the request.

Method `dna_sign` is not designed for the transaction signing. This method can only sign a random text string. You can see [here](https://github.com/idena-network/idena-go/blob/master/blockchain/types/transaction_signing.go#L13) how transactions are signed. You need to calculate `sha3` hash from params array and then sign it on your own.

Please, take a look at ethereum `web3.js` library.

**Comment by menxit** [comment]
Hi,
I'm using ethers.js but I think it's the same thing for my purpose (let me know if web3.js is mandatory).

So this is what I'm doing.

1. First of all I forge tx.
```
const forgedTx = RLP(data);
```
Where data is:
```
[
	1001,											// nonce
    41,												// epoch
    0,												// type
    0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0", 	// to
    0.001,											// amount
    0.00000000000003, 								// maxFee
    0,												// tips
    "0x", 											// payload
    "0x", 											// signature
}
```
I'm pretty sure that I'm correctly forging the tx, because it is the same result that I obtain from `bcn_getRawTx`.
```
0xe88203e9298094ca62b708b16ea6223d29ea6d2a7f4db5cb9e34c087038d7ea4c68000827530808080
```

2. Now, I sign the forgedTx:
```
const wallet = new ethers.Wallet(privateKey);
const hash = ethers.utils.keccak256(forgedTransaction);
const signature = wallet.signMessage(hash);
```
```
307839386533316238333963303631666665353935633232626433646636363536633662303938393836653934373362633266393530346534306539373131396132323432616534633631363639336638356662623130623532643330643730663863633039633062643065343264353737633334633765353130306462616334643163
```

3. Now I encode using RLP the transaction attaching the signature as showed [here](https://github.com/idena-network/idena-go/blob/master/blockchain/types/transaction_signing.go#L13).
```
f8ad8203e9298094ca62b708b16ea6223d29ea6d2a7f4db5cb9e34c087038d7ea4c680008275308080b884307839386533316238333963303631666665353935633232626433646636363536633662303938393836653934373362633266393530346534306539373131396132323432616534633631363639336638356662623130623532643330643730663863633039633062643065343264353737633334633765353130306462616334643163
```

4. Finally I inject the transaction using the `bcn_sendRawTx`, but now an "invalid signature" message is raised.
```
{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32000,
        "message": "invalid signature"
    }
}
```

**Comment by ridenaio** [comment]
[Here](https://github.com/idena-network/idena-go/blob/master/blockchain/types/transaction_signing.go#L56) you can see which fields are required for signature. All numeric fields, like amount, should be 10**18. Moreover, you add `"0x", // signature`, but you should avoid this field when calculating signature

**Comment by menxit** [comment]
Yes, I'm using 10**18 (forgot pasting parsed results).
Also I tried to avoid "0x" of signature as suggested, but I still receive an "invalid signature" error.

This is what I'm signing:
```
[
  1001,
  41,
  0,
  '0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0',
  1000000000000000,
  30000,
  0,
  '0x' // payload
]
```
And what I encode before injection:
```
[
  1001,
  41,
  0,
  '0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0',
  1000000000000000,
  30000,
  0,
  '0x',
  '0x307838323530616130346465653635653363313335323364373638653739383763376534323630616139333136656566656134636662333561623966333537636237343664663237313664636533333535646466343239326532383366306630303738353630363761663261366334356439316130356563653532303363656264363163'
]
```

Result:
```
{"code":-32000,"message":"invalid signature"}
```

**Comment by menxit** [comment]
I created a sandbox letting you to reproduce the error. There is a clear private key to make easier to reproduce error (please do not steal my 0.99 DNA internet!).

The only thing to do to obtain the invalid signature error is to click on run.

I hope this can help to catch my mistake.

https://repl.it/repls/SillyStudiousInteger

**Comment by sidenaio** [comment]
Method [signMessage](https://github.com/ethers-io/ethers.js/blob/master/wallet.js#L89) is the same as dna_sign. You should invoke signing like [this](https://github.com/ethers-io/ethers.js/blob/master/wallet.js#L85) somehow.

**Comment by ridenaio** [comment]
This is working example, try it please:
```
const RLP = require('rlp');
const ethers = require('ethers');
const { SigningKey } = require('ethers/utils/signing-key');

function createTransaction() {
  const data = [
    1, // nonce
    41, // epoch
    0, // type
    '0x02bD24aD70C2335F5B3FE47bfcE8eD6e39D447CB', // to
    1, // amount (0.000000000000000001)
    10000, // max fee (0.000000000000010000)
    null, // tips
    '0x', // payload (can be null too)
  ];

  const rlpData = RLP.encode(data);
  const hash = ethers.utils.keccak256(rlpData);

  var key = new SigningKey('<your key here>');

  const sig = key.signDigest(hash);

  const joinedSignature = Buffer.concat([
    Buffer.from(sig.r.substr(2), 'hex'),
    Buffer.from(sig.s.substr(2), 'hex'),
    Buffer.from([0]),
  ]);

  const res = [...data, joinedSignature];
  const rlpResult = RLP.encode(res);
  console.log(rlpResult.toString('hex'));
}

createTransaction();
```

**Comment by ProjXDev** [comment]
Hello .. i am trying to do the same thing but using PHP .. but there is something wrong with class i am trying to edit ,, here it is my code..
`<?php

namespace kornrunner\Ethereum;

use kornrunner\Keccak;
use kornrunner\Secp256k1;
use RuntimeException;
use Web3p\RLP\RLP;
use kornrunner\Signature\Signature;


     
class Transaction {
    protected $nonce;
    protected $epoch;
    protected $maxfee;
    protected $to;
    protected $amount;
	protected $tips;
    protected $payload;
   
  
    protected $r = '';
    protected $s = '';
    protected $v = '';


                      
    public function __construct( string $nonce = '',string $epoch = '',string $to ='',string $amount = '', string $maxfee = '',string $tips ='',string $payload ='') {
        $this->nonce = $nonce;
        $this->epoch = $epoch;
		
        $this->to = $to;
        $this->amount = $amount;
		$this->maxfee = $maxfee;
		$this->tips =$tips;
		$this->payload =$payload;
    
    }

    public function getInput(): array {
        return [
            'nonce' => $this->nonce,
			'epoch' => $this->epoch,
            
            'to' => $this->to,
            'amount' => $this->amount,
			'maxfee' => $this->maxfee,
			'tips'  => $this->tips,
			'payload'  => $this->payload,
            'v' => $this->v,
            'r' => $this->r,
            's' => $this->s,
        ];
    }

    public function getRaw(string $privateKey, int $chainId = 0): string {
        if ($chainId < 0) {
            throw new RuntimeException('ChainID must be positive');
        }

        $this->v = '';
        $this->r = '';
        $this->s = '';

        if (strlen($privateKey) != 64) {
            throw new RuntimeException('Incorrect private key');
        }

        $this->sign($privateKey, $chainId);

        return $this->serialize();
    }

    private function serialize(): string {
        return $this->RLPencode($this->getInput());
    }

    private function sign(string $privateKey, int $chainId): void {
        $hash      = $this->hash($chainId);

        $secp256k1 = new Secp256k1();
        /**
         * @var Signature
         */
        $signed    = $secp256k1->sign($hash, $privateKey);

        $this->r   = $this->hexup(gmp_strval($signed->getR(), 16));
        $this->s   = $this->hexup(gmp_strval($signed->getS(), 16));
        $this->v   = dechex ((int) $signed->getRecoveryParam () + 27 + ($chainId ? $chainId * 2 + 8 : 0));
    }

    private function hash(int $chainId): string {
        $input = $this->getInput();

        if ($chainId > 0) {
            $input['v'] = $chainId;
            $input['r'] = '';
            $input['s'] = '';
        } else {
            unset($input['v']);
            unset($input['r']);
            unset($input['s']);
        }

        $encoded = $this->RLPencode($input);

        return Keccak::hash(hex2bin($encoded), 256);
    }

    private function RLPencode(array $input): string {
        $rlp  = new RLP;

        $data = [];
        foreach ($input as $item) {
            $amount  = strpos ($item, '0x') !== false ? substr ($item, strlen ('0x')) : $item;
            $data[] = $amount ? '0x' . $this->hexup($amount) : '';
        }

        return $rlp->encode($data);
    }

    private function hexup(string $amount): string {
        return strlen ($amount) % 2 === 0 ? $amount : "0{$amount}";
    }

}
`

`<?php

require './vendor/autoload.php';
use kornrunner\Ethereum\Transaction;



      $to = '0x...addr';
      $amount = '1';
      $maxFee = '10000';
      $tips = '0';
      $nonce = '326';
      $epoch = '41';
      $payload = '0x';
      $type = '0';
$privateKey = '..';


$transaction = new Transaction ($nonce,$epoch,$type,$to,$amount,$maxFee,$tips,$payload);

echo $transaction->getRaw ($privateKey);





 ?>
`

**Comment by ProjXDev** [comment]
Hello .. i am trying to do the same thing but using PHP .. but there is something wrong with class i am trying to edit ,, here it is my code..


` namespace kornrunner\Ethereum;

use kornrunner\Keccak;
use kornrunner\Secp256k1;
use RuntimeException;
use Web3p\RLP\RLP;
use kornrunner\Signature\Signature;


     
class Transaction {
    protected $nonce;
    protected $epoch;
    protected $maxfee;
    protected $to;
    protected $amount;
	protected $tips;
    protected $payload;
   
  
    protected $r = '';
    protected $s = '';
    protected $v = '';


                      
    public function __construct( string $nonce = '',string $epoch = '',string $to ='',string $amount = '', string $maxfee = '',string $tips ='',string $payload ='') {
        $this->nonce = $nonce;
        $this->epoch = $epoch;
		
        $this->to = $to;
        $this->amount = $amount;
		$this->maxfee = $maxfee;
		$this->tips =$tips;
		$this->payload =$payload;
    
    }

    public function getInput(): array {
        return [
            'nonce' => $this->nonce,
			'epoch' => $this->epoch,
            
            'to' => $this->to,
            'amount' => $this->amount,
			'maxfee' => $this->maxfee,
			'tips'  => $this->tips,
			'payload'  => $this->payload,
            'v' => $this->v,
            'r' => $this->r,
            's' => $this->s,
        ];
    }

    public function getRaw(string $privateKey, int $chainId = 0): string {
        if ($chainId < 0) {
            throw new RuntimeException('ChainID must be positive');
        }

        $this->v = '';
        $this->r = '';
        $this->s = '';

        if (strlen($privateKey) != 64) {
            throw new RuntimeException('Incorrect private key');
        }

        $this->sign($privateKey, $chainId);

        return $this->serialize();
    }

    private function serialize(): string {
        return $this->RLPencode($this->getInput());
    }

    private function sign(string $privateKey, int $chainId): void {
        $hash      = $this->hash($chainId);

        $secp256k1 = new Secp256k1();
        /**
         * @var Signature
         */
        $signed    = $secp256k1->sign($hash, $privateKey);

        $this->r   = $this->hexup(gmp_strval($signed->getR(), 16));
        $this->s   = $this->hexup(gmp_strval($signed->getS(), 16));
        $this->v   = dechex ((int) $signed->getRecoveryParam () + 27 + ($chainId ? $chainId * 2 + 8 : 0));
    }

    private function hash(int $chainId): string {
        $input = $this->getInput();

        if ($chainId > 0) {
            $input['v'] = $chainId;
            $input['r'] = '';
            $input['s'] = '';
        } else {
            unset($input['v']);
            unset($input['r']);
            unset($input['s']);
        }

        $encoded = $this->RLPencode($input);

        return Keccak::hash(hex2bin($encoded), 256);
    }

    private function RLPencode(array $input): string {
        $rlp  = new RLP;

        $data = [];
        foreach ($input as $item) {
            $amount  = strpos ($item, '0x') !== false ? substr ($item, strlen ('0x')) : $item;
            $data[] = $amount ? '0x' . $this->hexup($amount) : '';
        }

        return $rlp->encode($data);
    }

    private function hexup(string $amount): string {
        return strlen ($amount) % 2 === 0 ? $amount : "0{$amount}";
    }

}`



` require './vendor/autoload.php';
use kornrunner\Ethereum\Transaction;



      $to = '0x...addr';
      $amount = '1';
      $maxFee = '10000';
      $tips = '0';
      $nonce = '326';
      $epoch = '41';
      $payload = '0x';
      $type = '0';
$privateKey = '..';


$transaction = new Transaction ($nonce,$epoch,$type,$to,$amount,$maxFee,$tips,$payload);

echo $transaction->getRaw ($privateKey);

`

**Comment by menxit** [comment]
Wow, thank you!

**Comment by ridenaio** [comment]
Can we close the issue now? Do you have any other questions?

**Comment by menxit** [comment]
One last question. I was playing with transactions and I found a strange behaviour.

1. I send tx with amount `0.0001` and nonce `n`.
2. I don't wait for confirmation of this tx and I send the same tx withe the same amount and nonce. Node raises an error and it seems the right behaviour.
```
{"code":-32000,"message":"tx with same hash already exists"}
```
3. I send another tx (before the confirmation of first one) incrementing sent amount to 0.001. Node raises an "insufficient funds error" (event if my balance is enough). I'm not sure that an error should be raised (e.g. in Ethereum I can send multiple tx with the same nonce and miners will choose the one with higher fees), anyway I think error message shouldn't be "insufficient funds", but something like "nonces can't be used multiple times".
```
{"code":-32000,"message":"insufficient funds"}
```

**Comment by ridenaio** [comment]
Could you please give all your parameters for the first and second transactions?

**Comment by menxit** [comment]
# Tx 1
[
  1036,
  41,
  0,
  '0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0',
  100000000000,
  30000,
  0,
  '0x'
]
`injected`

# Tx 2 [tx with same hash is required to cause insufficient funds error]
[
  1036,
  41,
  0,
  '0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0',
  100000000000,
  30000,
  0,
  '0x'
]
`{"code":-32000,"message":"tx with same hash already exists"}`

# Tx 3
[
  1036,
  41,
  0,
  '0xCa62b708B16eA6223D29Ea6D2A7F4dB5cB9E34C0',
  1000000000000,
  30000,
  0,
  '0x'
]
`{"code":-32000,"message":"insufficient funds"}`

**Comment by menxit** [comment]
Node version: `idena version 0.19.0`

**Comment by menxit** [comment]
I updated to `idena version 0.19.1` and retried the sequence of three txs, same behaviour.

**Comment by ridenaio** [comment]
Oh, yes, the code above has one mistake, sorry for that. Please see the difference in `joinedSignature `calculation: 
```
  const joinedSignature = Buffer.concat([
    Buffer.from(sig.r.substr(2), 'hex'),
    Buffer.from(sig.s.substr(2), 'hex'),
    Buffer.from([sig.recoveryParam]),
  ]);
```

Currently, the random transaction will be mined, if you send different transactions with the same nonce. Our fee model is different from ethereum, the fee is static, so miners can choose transactions with better tips. In the nearest future, we will add sorting by `tips`, so, the transaction with the highest tips will be chosen by default.

**Comment by menxit** [comment]
Great, I can close :)
