### ISSUE TITLE
Get NULL result if using bcn_transactions if input other address

### ISSUE THREAD

**Issue by codev911** [idena-network/idena-go#373]
Hei, i have issue about how to get other wallet transaction view in my node is return NULL value after i try to send it. I have try to view last transaction with generated address from node. It get clear result about it.

1. Body JSON from Internal node wallet

```
{
  "method": "bcn_transactions",
  "params": [
    {
      "address": "0xbd5ca7ee8b302deb0a1a7f72b02efb52ed7fe86e",
      "count": 1
    }
  ],
  "id": 1
}
```
2. Result JSON from Internal Wallet is OK
```
{
  "jsonrpc": "2.0",
  "id": 25,
  "result": {
    "transactions": [
      {
        "hash": "0xaf317c97e2ec6d1e56eefa5cead314816864d6cac0003bdac6d1835738024352",
        "type": "send",
        "from": "0x203d4fe4b4ba9c496bafe376603aada1004817f1",
        "to": "0xbd5ca7ee8b302deb0a1a7f72b02efb52ed7fe86e",
        "amount": "0.19999988888",
        "tips": "0",
        "maxFee": "0.000000000000021",
        "nonce": 1,
        "epoch": 42,
        "payload": "0x",
        "blockHash": "0xb5fe9ac1c82838a0bebf6595906fe8a07866a668e6af9bce1d413293a1fc8823",
        "usedFee": "0.0000000000000107",
        "timestamp": 1586795532
      }
    ],
    "token": "0x6f7469bd5ca7ee8b302deb0a1a7f72b02efb52ed7fe86e000000005e94573400000001"
  }
}
```
3. Body JSON from other wallet
```
{
  "method": "bcn_transactions",
  "params": [
    {
      "address": "0x203d4fe4b4ba9c496bafe376603aada1004817f1",
      "count": 1
    }
  ],
  "id": 2
}
```
4. Result JSON from Other Wallet is NULL
```
{
  "jsonrpc": "2.0",
  "id": 26,
  "result": {
    "transactions": null,
    "token": null
  }
}
```

please take a look to this or you may give me solution about it, thanks

https://github.com/idena-network/idena-go/blob/6d999a102575ee946903cca2507df606c71462a2/api/blockchain_api.go#L237

**Comment by codev911** [comment]
please send me some DNA for coffe : 0xbd5ca7ee8b302deb0a1a7f72b02efb52ed7fe86e

**Comment by ridenaio** [comment]
Currently, `bcn_transactions` method works only with coinbase address. In the next releases, we are planning to add support for additional accounts in the Idena desktop application and this method will also return transactions from these accounts.

**Comment by andridevk911** [comment]
i hope this week will available

**Comment by andridevk911** [comment]
this method still for `coinbase` only @ridenaio ?
i have test but still null result

**Comment by sidenaio** [comment]
Yes, this method works for coinbase only

**Comment by andridevk911** [comment]
how to get latest hash transaction from `account_list` ? any solution ? @ridenaio @sidenaio

**Comment by EarthlingDavey** [comment]
Hi I've built from src today and this issue still persists.

I've tried requests and get responses that are the same as in the original post.

**Comment by EarthlingDavey** [comment]
Hey, @ridenaio can you give some guidance on your merged pull request. 

I still get this for addresses except coinbase.

```
{
    "jsonrpc": "2.0",
    "id": 2,
    "result": {
        "transactions": null,
        "token": null
    }
}
```

@codev911 did you use the recent code to get a good result?

I'l davey on Idena Discord and EarthlingDavey on TG.

**Comment by ridenaio** [comment]
Hi, this method works only with your addresses:
- coinbase address
- accounts from `account_list` RPC method

If you want to get transactions from external addresses, you need to index blocks one by one by yourself.

**Comment by EarthlingDavey** [comment]
ok, thanks for the explanation, and for your work on Idena codebase :)
