### ISSUE TITLE
Connect to remote node and client displays node version 0.0.1 + "run built-in node"-display 

### ISSUE THREAD

**Issue by GiraeffleAeffle** [idena-network/idena-go#383]
I did the following steps on a Raspberry Pi4 Model B:

1. git clone https://github.com/idena-network/idena-go
2. cd idena-go
3. go build
4. then replaced the ~/datadir/keystore/nodekey with the one on my laptop in %appdata%\idena\node\datadir\keystore\nodekey
5. copied the ~/datadir/api.key and paste it into the field of "Node api key" in the idena client(click on settings and then connect to remote node) and press save.
6. Get the ip address of my raspberry pi
7. Then type http://MY_IP:9009 into the field of "Node address" over the "Node api key" in the idena client and press save.
8. Then start the node on the pi in the folder ~/idena-go with ./idena-go --rpcaddr MY_IP
9.  Now the client synchronizes and runs and mines dna. 
10. You can see the Node version being 0.0.1
11. Is that just a display problem or how do I actually download the newest Version of the node?
12. Also if you activate "connect to remote node" button, the "run built-in node" doesn't turn off automatically. Only one of them should be turned on, but I think this is also only a display issue.
![image](https://user-images.githubusercontent.com/48856967/79686880-d703ed80-8243-11ea-9000-6c58f50cf42c.png)

**Comment by ridenaio** [comment]
When you build the node from source code, version is always 0.0.1. If you want to change it, use build flags, `go build -ldflags "-X main.version=<your version>"`

**Comment by GiraeffleAeffle** [comment]
@ridenaio but is it the actual version 0.0.1 or just a matter of displaying it wrongly? Because I have an api.key and so on to chose and someone told me that old version didn't even have that function.

**Comment by GiraeffleAeffle** [comment]
After I did that my flips that i did for the next validation are now missing in the published folder and are now placed in the archived folder. What should I do? :/

![image](https://user-images.githubusercontent.com/48856967/79809841-ce113a00-8371-11ea-8274-778d04447663.png)

**Comment by ridenaio** [comment]
When you change the version, the code reacted as it was a fork. That's why your `idenachain.db` folder inside `datadir` was cleaned. You have already done your flips, your flips are in the chain, and you can see in your client that you have 3 published flips now. So, don't worry about missing icons. The behavior is the same as if you have run the node and the client on the new laptop.

**Comment by GiraeffleAeffle** [comment]
> When you change the version, the code reacted as it was a fork. That's why your `idenachain.db` folder inside `datadir` was cleaned. You have already done your flips, your flips are in the chain, and you can see in your client that you have 3 published flips now. So, don't worry about missing icons. The behavior is the same as if you have run the node and the client on the new laptop.

Thank you very much !! :)

**Comment by KruciferX** [comment]
> When you change the version, the code reacted as it was a fork. That's why your `idenachain.db` folder inside `datadir` was cleaned. You have already done your flips, your flips are in the chain, and you can see in your client that you have 3 published flips now. So, don't worry about missing icons. The behavior is the same as if you have run the node and the client on the new laptop.

We get many different bits and pieces so we cannot conclude what is the full truth and we surely don't want to risk finding that out during validation. If flips were published, are they fully on the network (in every node's DB or IPFS folder)?

Does that mean that I could, in theory, run a clean install of client and node, with just my existing nodekey, and all my submitted flips would be accessible to others during validation? Are my decryption keys still existing in that clean installation of client and node?

**Comment by ridenaio** [comment]
Flips are spreading among the network when you submit it. Each node `pin` (store) it locally with 50% probability (by default, you can see [here](https://github.com/idena-network/idena-go/blob/master/config/ipfs.go#L22)). Moreover, our bootstrap nodes have custom configurations and pin **all** flips locally. 

Flip decryption keys are generated from the static string, signed with your private key. So, if you transfer your `nodekey` file to another computer, flip decryption keys will be the same.

Regarding your question, you can do a clean install of the client and node with your existing `nodekey` and all your flips will be accessible during the validation.

**Comment by KruciferX** [comment]
Thank you very much for your answer. This issue can now be closed (again :) ).
