### ISSUE TITLE
Idena Discord Webhook

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-go#387]
There were plans to add Webhook to Idena Discord server. Is this possibility still open?

[https://discordapp.com/api/webhooks/701078917674696724/7xJsS5udRoFsItdykBUaIpivOHVwYlR1uUftiRmQIM6QA_SQkUCjaoXtqw5pfvAFlh6g](url)

[https://superuser.com/questions/1189901/can-i-integrate-a-discord-channel-with-github-pull-requests](url)

**Comment by ridenaio** [comment]
We have added WebHook to the Idena organization. Please, check it.

**Comment by KruciferX** [comment]
All good, thanks!
