### ISSUE TITLE
Validation can't load flips if node was restarted before validation

### ISSUE THREAD

**Issue by jessidy** [idena-network/idena-go#390]
Node was restarted before validation period 5 minutes (red warning message appeared in idena-desktop), peers found in 20-30 seconds and blocks sync ok

node version 0.19.4

When validation starts, in log was error messages:

> WARN [04-22|13:30:01.485] flip is not ready                        err="flip private key is missing" cid=bafkreigjyqexk6hc4xm2wusou3dswb5epuaqib6w2vlbbld5g4dpkgcpku

i think ipfs network need more time to connect? may be idena-desktop must show warning about it?

**Comment by ridenaio** [comment]
Hi, did you fail your validation? This log is normal because your node did not manage to receive the key yet. Maybe this key was propagating through the network, or the author did not appear on validation sessions and did not send this key to you.

**Comment by jessidy** [comment]
ALL flips was not loaded, too many errors like this in log. Yes, validation failed (i.e. skipped, identification status changed from 'verified' to 'suspended')

**Comment by ridenaio** [comment]
It is hard to say something without any log files. Please, write your address and attach log files, both, from UI and node, for further investigation.

**Comment by jessidy** [comment]
it's too late, the logs are cropped and i am not saved it, my fault

**Comment by ridenaio** [comment]
Can we close this issue now? Or you have some other questions?

**Comment by jessidy** [comment]
as you wish
