### ISSUE TITLE
Anyone can run many nodes with the same nodekey

### ISSUE THREAD

**Issue by hillhero789** [idena-network/idena-go#394]
Currently, anyone can run many nodes with the same nodekey, I think this will seriously affect network security, especially when idena become sharding network.

**Comment by KruciferX** [comment]
Multiple nodes with same nodekey only hurt that nodekey's address with diminished mining rewards cause of sync errors.

**Comment by midenaio** [comment]
Running the multiple nodes with the same address leads to the double voting and double block proposing which reduces mining rewards. In addition double voting penalty will be introduced in the further releases.
