### ISSUE TITLE
Flip details

### ISSUE THREAD

**Issue by ProjXDev** [idena-network/idena-go#400]
Hi , Is there a way to get a flip details ? Like who solved it and did he report or not ? And if that is in the short and long answers hash then how to parse it ? ..I hope that the rpc can get these details

**Comment by ridenaio** [comment]
Hi, you can get all information from our [explorer](https://scan.idena.io). There are no such RPC methods. If you want to get it manually you need to parse payload from all `SubmitShortAnswersTx` and `SubmitLongAnswersTx` transactions and calculate it by yourself.

How short answers are encoded you can find [here](https://github.com/idena-network/idena-go/blob/master/api/flip_api.go#L223).
How long answers are encoded you can find [here](https://github.com/idena-network/idena-go/blob/master/api/flip_api.go#L246).

**Comment by ProjXDev** [comment]
Okey  thanks for the fast reply😁😀
