### ISSUE TITLE
No peers when using IpfsConf Profile "server"

### ISSUE THREAD

**Issue by vlddm** [idena-network/idena-go#407]
Peer search are never successful when using [config.json](https://github.com/idena-network/idena-go#json-config) provided in Readme.md with latest 0.19.6 node on Linux.
Looks like problem is IpfsConf, sync was started after this section was removed:
```
  "IpfsConf": {
    "Profile": "server",
    "IpfsPort": 40405,
    "BootNodes": [],
    "BlockPinThreshold": 0.3,
    "FlipPinThreshold": 0.5
  }
```

**Comment by ProjXDev** [comment]
Hey .. the bootnodes array is empty you have to add at least one :)
