### ISSUE TITLE
indena-node freezed

### ISSUE THREAD

**Issue by Rinzler78** [idena-network/idena-go#413]
Hi,

I’m on idena since last Week.
idena-node 0.19.6 installed on an Ubuntu docker hosted by a Synylogy NAS.
Idena client 0.9.4 is installed on my Mac.
Ma Syno is a DS716+ With 2GB RAM. The ubuntu Docker does not have RAM limitation and use less than 400Mb.
Everything worked well until tonight.

Idena-node seems to have been disconnected from the network, between 2:38 AM and 6:26 AM, 
where it seems to have been freezed

The Docker was not down, I have been able to log on it (ssh) but the console showing (**channel 3: open failed: connect failed: Connection refused**) multiple times.

![image](https://user-images.githubusercontent.com/3533190/81313964-d7e0b000-9088-11ea-9d86-2e2515d5a698.png)

Idena client couldn’t connect to node.

Finally I restart the docker and relaunch idena-node.
The synchronisation started but it was slow.
When sync was OK, my mining status have been reset.

I had over 6 DNA penalty.

Dont know why ?

Here is Full Logs:
[output.log](https://github.com/idena-network/idena-go/files/4593584/output.log)

Thks ;)

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
