### ISSUE TITLE
syncing is terrible

### ISSUE THREAD

**Issue by Pascal-J** [idena-network/idena-go#433]
I first installed 1 day before 10.0.  Perhaps 20.0 node was installed midway through that first day.  Was high bandwidth use, but it did sync whole chain.

After 10.0, it doesn't seem to fully sync, but does manage slowly/sporadically to sync jump by exactly 1000 ... block  xxxx333

Errors include:

error while writing to stream, id, err="connection write timeout"

Post consuming error component=downloader err="snapshot's downloading has been failed: ipfs load: context canceled"

process batch - timeout was reached component=downloader

I tried the "mining not stable" workaround at https://rioda.org/idena/faq_tutorials.php with longer timeouts, but no help

**Comment by Pascal-J** [comment]
Have 5-6mbits down, 0.1-0.2mbits up.

Did find some success by quitting all other bandwidth uses.  Synced blocks went backwards to gain success.

**Comment by midenaio** [comment]
Is it still an issue?
