### ISSUE TITLE
Node repeatably accumulating peers to about 60-70 and than dropping it to 36.

### ISSUE THREAD

**Issue by vlddm** [idena-network/idena-go#471]
Using 0.21.0
My config.json:
```
    "MaxInboundPeers": 50,
    "MaxOutboundPeers": 50
```
Node repeatably accumulating peers to about 60-70 and than dropping it to 36.
Is it normal behavior?

**Comment by ridenaio** [comment]
Hi, node peering works on the top of IPFS peering system. Idena node IPFS, by default, has two config values `LowWater` and `HighWater`, which are set to 30 and 50. IPFS starts to clean connections if the amount is more than 50. So, if IPFS cleans the connection, then the corresponding node "peer" is also cleaned and disconnected.

To prevent this situation, try to set another IPFS water params in the node config file:

```
"IpfsConf": {
    "LowWater": 100,
    "HighWater": 150
}
```
