### ISSUE TITLE
Node errors

### ISSUE THREAD

**Issue by nikolakurtic** [idena-network/idena-go#476]
I have done my first validation and after that node cannot sync:

`ERROR[06-22|14:30:07.637] invalid flip                             err="tx can't be accepted due to validation ceremony"
WARN [06-22|14:30:08.936] Do not have requested block              id=QmfC818tNe3vDmsnaViyHcdfWYevcPPArAw8gxB1sQrdcW height=1450956
`
from block explorer I see that I passed:
[https://scan.idena.io/address/0xf4c8f91cbc59d3193886447a9cb5f06097ef2305](url)

**Comment by ridenaio** [comment]
Please, send logs. Errors above should not affect the sync process.
