### ISSUE TITLE
Node crashes (panics?)

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#484]
Hello, I have setup node on a$5 Vultr VPS. Idea was to leave it running to help the network out with peering and bandwidth.
- it has no identity attached to it
- no mining
- BlockPinThreshold 1, FlipPinThreshold 1, Profile: server, MaxInboundPeers 18, MaxOutboundPeers 18, FastSync true
- latest node version
- ubuntu 18.04
- clean VPS, just that one node is running, nothing else

Latest entry in the log is:
INFO [07-04|20:14:42.502] Node is synchronized                     component=downloader

I guess at that time people are starting syncing their nodes (new people, people that are mining on one pc and then validating on second 🤦‍♂️) and the network gets busy.
Here are full [logs.zip](https://github.com/idena-network/idena-go/files/4877703/logs.zip)

I guess this is simmilar thing to a long forgotten https://github.com/idena-network/idena-go/issues/232
After that fix, i did not run node in a loop, it just was rock stable. Now we need to run node in a loop until this is fixed. I won't run my node in loop so i get notification about when this happen and to see how often it happens. It was not just my one node, it happened to others that I'm monitoring for family members.
If people run node on VPS by my guide they were in problem without loop, if they used idena-manager, it auto restarted it. Im not sure how it acts in client, does it auto restart's it.

Explorer did show lot of offline penalties yesterday before validation
![Capture](https://user-images.githubusercontent.com/37978870/86575832-266ed580-bf78-11ea-9f5d-fe52202e9add.PNG)

Graphs from vultr console that are showing its activity...

![par-bandw](https://user-images.githubusercontent.com/37978870/86573876-481a8d80-bf75-11ea-9799-f0cad83e8a86.PNG)
![par-cpu](https://user-images.githubusercontent.com/37978870/86573899-510b5f00-bf75-11ea-8e58-c0513bab22c6.PNG)
![par-disk-operation](https://user-images.githubusercontent.com/37978870/86573914-536db900-bf75-11ea-9356-84bcf1ec5c3f.PNG)
![par-network](https://user-images.githubusercontent.com/37978870/86573921-55377c80-bf75-11ea-8949-bd7a85594202.PNG)

And even more graphs 😄 luckly these 2 did not crash, just went out of sync from time to time on validation day

**Node1 with identity, mining on, Digital ocean, $5 droplet**
![mirko1](https://user-images.githubusercontent.com/37978870/86576589-376c1680-bf79-11ea-87a6-e514315070b6.PNG)
![mirko2](https://user-images.githubusercontent.com/37978870/86576596-3aff9d80-bf79-11ea-997e-176820a74f9e.PNG)
![mirko3](https://user-images.githubusercontent.com/37978870/86576606-3d61f780-bf79-11ea-9319-0fbbfb8fd1a3.PNG)

**Node2 with identity, mining on, Digital ocean, $5 droplet**
![nada1](https://user-images.githubusercontent.com/37978870/86576621-42bf4200-bf79-11ea-9d91-91cffd9e0e26.PNG)
![nada2](https://user-images.githubusercontent.com/37978870/86576632-45219c00-bf79-11ea-8cb6-e1622579ceb3.PNG)
![nada3](https://user-images.githubusercontent.com/37978870/86576640-4783f600-bf79-11ea-944b-1f4bcc051361.PNG)

**Comment by ridenaio** [comment]
Hi, how often your VPS node fails? Could you please try to run VPS node with `./idena-go > full.log 2>&1` command, to catch possible panic?

If you have friends with built-in node, which fails too, panic log can be found in `%appdata%/Idena/node/datadir/logs/error.log` file.

**Comment by rioda-org** [comment]
I have added full logging on that VPS, no crashes in the past 24h. Will bring logs if crash happen.

In the mean-time I got logs from one of our member running built in node on arch linux.
[error-output.zip](https://github.com/idena-network/idena-go/files/4919467/error-output.zip)

![unknown](https://user-images.githubusercontent.com/37978870/87440347-27e07380-c5f2-11ea-9a9d-72af17782085.png)

**Comment by ridenaio** [comment]
LevelDb got error `too many open files`:
```
panic: open /home/bren/.config/Idena/node/datadir/idenachain.db/001156.ldb: too many open files
```

Node, on start, always tries to increase the number of opened files by increasing ulimit. In logs above I see that the limit was increased to 4096 `Set new fd limit value=4096`, but for some reason, it did not help or did not change. You can try to increase it in your Linux configuration to avoid this problem in the future.

**Comment by rioda-org** [comment]
New logs from windows user:
windows 10. Local. Built-in node. All updated. Connection speed steady, Lan-cable, around  6-8mb/s.

[LOGS.zip](https://github.com/idena-network/idena-go/files/4928204/LOGS.zip)

**Comment by ridenaio** [comment]
This user has several errors connected with memory allocation.
The last error is:
```
runtime: VirtualAlloc of 259719168 bytes failed with errno=1455
fatal error: out of memory
```
How much RAM does user have?

**Comment by rioda-org** [comment]
This is not happening anymore... closing
