### ISSUE TITLE
Mr.Bubbles - sync problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#486]
https://discord.com/channels/634481767352369162/634481767843364866/729248184290902066

I'm on Mac, I downloaded new app version 14.2 and with it I can't switch off mining status, once trying to switch off-it starts synchronizing, then after complete synchro-again status is on. And again and again. Tried 3 times and got success on 3d time, but after mining got switched off, again synchro.
It started when I downloaded 14.2.

[mr_bubbles.zip](https://github.com/idena-network/idena-go/files/4885302/mr_bubbles.zip)

Rioda: I'm not sure where to open which issue, desktop, or node repo...

**Comment by ridenaio** [comment]
It seems that build-in node sometimes panics. Please, attach logs from `%appdata%/Idena/node/datadir/logs/error.log` to identify the issue.

**Comment by rioda-org** [comment]
he said
"thx for the help, if this bug will appear again, will do."
CLOSE...
