### ISSUE TITLE
Rayyan - validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#492]
From Rayyan from discord
https://discord.com/channels/634481767352369162/634481933803585546/729340598967861258

"I completed my 6 flips 30 seconds in advance. My long test 15 minutes in advance. Everything was working fine.
My validation failed cause it said: Late submission
Validation answers are all there.
Got all the questions right with strong consensus.
In addition the transactions took place."

[Rayyan.zip](https://github.com/idena-network/idena-desktop/files/4880221/Rayyan.zip)

![JPEG_20200705_072119](https://user-images.githubusercontent.com/37978870/86618090-9735e200-bfb8-11ea-901e-7b177c9ec026.jpg)
![JPEG_20200705_073501](https://user-images.githubusercontent.com/37978870/86618092-98ffa580-bfb8-11ea-98ee-6b9207e025d7.jpg)

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
