### ISSUE TITLE
FlanelBigMac - validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#493]
This is collected from a user FlanelBigMac on discord:
"-latest update
-synchronized an hour before validation
-running off my laptop, not vps
-i have 1000mb internet

A minute or two before validation, there was another synchronization out of nowhere, i heard this happened to a couple people, and then when validation started, nothing was loading for me"

[FlanelBigMac.zip](https://github.com/idena-network/idena-desktop/files/4878337/FlanelBigMac.zip)

![Screenshot_85](https://user-images.githubusercontent.com/37978870/86584324-04c81b00-bf85-11ea-98c5-fa63f566955a.png)

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
