### ISSUE TITLE
Suggestion: To redistribute invites the way it was before humans were introduced but make human's reward 1.5x of verified

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-go#498]
It seems that current invites distribution is clogging the network growth. Indeed, it concentrate all invites in hands of best and fastest flip solvers. Initially it was made for preventing bots from collecting invitations and solving flips randomly (https://medium.com/idena/idena-security-model-update-7d624ef3298f). But I don't think it is a big problem anymore due to discrimination of Newbies and Lottery-based rewards for non-spent invitations.

I suggest to distribute invites the way it was before humans were introduced, 1 invite to every account with Verified status or higher. Human's overall rewards should be 1.5x higher than Verified's one in order to keep Human as desirable status. It means that reward for flips, invites and validation is 1.5 times higher for Human than for Verified or Newbie.

I want to add that main purpose of the protocol should be filtering out people from bots and not individuals who manage to solve flips better and quicker than the others. For example I am 14 epochs old and yet stay Verified (I created 48 out of 48 good flips with strong consensus). I even know identities (https://scan.idena.io/identity/0x8b8C0607c9AE92B567ADef452e79DC673C3c180D) who break this table here (https://miro.medium.com/max/1400/1*oD89Jqp0yfa8K6B5MKBcSA.png) being Verified for 43 epochs already. I know some other people with the same problem of not being able to get this 92% Score managing strictly 1 node. I don't mind to stay Verified forever as it probably will happen but I think that privileges of two invites for humans with corresponding rewards are too huge, let alone more easy multi-accounting for them.

**Comment by midenaio** [comment]
The issue will be closed. Feel free to reopen it if needed.
