### ISSUE TITLE
Suggestion: Score to be calculated as trailing average for last 5 epochs

### ISSUE THREAD

**Issue by Gutalean** [idena-network/idena-go#499]
This feature is needed for multi-accounting preventing and increase of vertical mobility in old identities status. As far as I know 'human' now became a status with the highest number of multi-accounts holders. Indeed, 'human' status gives you huge privileges over 'verified' in terms of rewards, invites and immunity to validation fail (humans are almost immortal in that sense). So in my opinion being 'human' you need to constantly prove that you deserve these privileges. And this should not depend on your previous 40 epochs history. That's why I suggest to calculate Score as trailing average for last 5 epochs only.

This will make multi-accounting harder for everyone, not only humans. Because the most frequent result of multi-node validation passing is not identities killing but rather some dips in one of your identities' Score. Currently if you have old enough identity these dips becomes negligible and you can continue your multi-accounting thing easily.

This measure will also make old identities pay more attention to quality of flips in the network.

Distribution of invites will be more up to date with the actual Scores of identities and not with their past long ago results.

**Comment by reb0rn21** [comment]
> The suggestion is very rational. It should not be such that one mistake remains 'for life'. Do not forget that the software and network are not perfect and errors happen!

Then you not understand this proposal does not fix you score at all, as soon you get bad flips and you will (as that is how luck work and flip lottery is pure random luck based) you score will drop
What original system have in benefit that it can not drop not rise FAST! so as human you are protected from chines and indian pure non sense flips some spam

If this system is adopted all humans with huge stakes over time will kill their identity as flip quality is NOT ready for score only in last 10 epoch! as luck is can very a lot and all would lose stake in future

**Comment by Gutalean** [comment]
One bad validation will not kill you rather just make your Score a little bit lower. If you fail your validations systematically you will become Verified temporary. Until you get you high Score back. Then you are Human again and have your invites back.

**Comment by reb0rn21** [comment]
you get how luck works, imagine in a year you and bus are human with 2000$ with stake... you score is 99% with new system...
for past 1 year you had over 100 gr8 flips (and luck of 500% over what is usual for whole system) and you tell yourself ohhh man my luck is so gr8
then human bot farms come, you luck turn as you should know luck always strive to be orbit at "100% of reality" and you get ~10+ bad flips in 6 epoch, you score is ~90% and you are zombie also as you failed last validation and in frustration what would you do as next failed mean you lose all you stake you got from past 2 years!

also look at explorer why so many 20+ epoch ppl killed their human? you think this change is gona make it better?

**Comment by midenaio** [comment]
The trailing score for the last 10 epochs is applied. I suppose this topic is no longer relevant. Otherwise feel free to reopen it.
