### ISSUE TITLE
Error "cannot send short answers tx"

### ISSUE THREAD

**Issue by melkir** [idena-network/idena-go#501]
During the validation the 18th July 2020, the following error came up, it prevented me from completing the consensus.

> 0|idena-node-linux-0.21  | ERROR[07-18|13:57:12.936] cannot send short answers tx             err="state nonce: 7, state epoch: 49, tx nonce: 7, tx epoch: 49: invalid nonce"

<img width="930" alt="Capture d’écran 2020-07-18 à 15 40 24" src="https://user-images.githubusercontent.com/3305685/87854019-f24bcb00-c90e-11ea-8759-e451fa77e964.png">

<img width="1192" alt="Capture d’écran 2020-07-18 à 15 44 34" src="https://user-images.githubusercontent.com/3305685/87854023-f5df5200-c90e-11ea-9923-d0b62317ab93.png">

Things I tried:
- Restart the node (`idena-node-linux-0.21.3`) and the client
- Use the previous version of the node (`idena-node-linux-0.21.2`)

Here's my identity if you need to investigate https://scan.idena.io/identity/0x9007f3427f63ca3b031ec8cb01979bc4ef71592c

**Comment by ridenaio** [comment]
Hi, please attach full node log file.

**Comment by melkir** [comment]
Where can I find the desktop application log on MacOS?
Unfortunately, I've destroyed the VPS server since my identity was suspended. I won't be able to recover the node log file 🙁

**Comment by midenaio** [comment]
> Where can I find the desktop application log on MacOS?
```
cd ~/Library/Logs/Idena
open .
```

**Comment by melkir** [comment]
Thanks @mbidenaio, here ya go
[idena.log](https://github.com/idena-network/idena-go/files/4946342/idena.log)

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
