### ISSUE TITLE
cryptovigi - validation problem

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#502]
cryptovigi had a short session late submission, node is on vps/ubuntu

[cryptovigi.zip](https://github.com/idena-network/idena-go/files/4942077/cryptovigi.zip)

![image](https://user-images.githubusercontent.com/37978870/87857857-2385c480-c92a-11ea-8eeb-43e4ba0ca394.png)

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
