### ISSUE TITLE
Suggestion : lite verification ceremony

### ISSUE THREAD

**Issue by nightfallinme** [idena-network/idena-go#517]
Hi,

I know this is not a suggestions tool but could be still better way to keep track of some suggestions.

I think there could be a way to make -soft- verification for non-node clients. IDENA looks for decentralization but still we could solve some smaller problems with a non-node client like mobile clients. 

there could be a lite verification ceremony, (before validation results are public )kicking in same time or a lagging period after real verificiation complete , a validation step that is only for lite clients which are non-node and much less resource hungry clients, they join ceremony, only solve flips(not creating) and they have to catch consensus side of flips. 

this liter version of validation could be used on less security needed activity if needed, maybe stuff that doesnt involve any economic value.

i think this will also help IDENA recognation as a project. creating a much bigger potential participant pool.

(adding a small amount of time to validation ceremony for lite clients to only solve flips and catch consensus side for a temp/soft or lite version of human status)

**Comment by midenaio** [comment]
Thank you for the proposal. However such changes don't look feasible for the current protocol implementation. The lite verification ceremony will require some number of flips which must be submitted by Idena participants in addition to the flips that created for the main validation ceremony. Feel free to reopen the issue if you have any other ideas on how to make it work.
