### ISSUE TITLE
Suggestion: apply graph theory algorithms on Oracles and the right to issue invites

### ISSUE THREAD

**Issue by ubiubi18** [idena-network/idena-go#520]
The upcoming oracle-feature is amazing, while in that context possible human farms (a bunch of people solving flips against payment for a single master who controls many nodes) get more problematic, because they disturbe honest voting. 

One single person should not have too much leverage on oracle votings!  

If there is a economic incentive to dominate a vote - no matter if it results in true data or wrong data oracle input - than it is likely that wrong data oracle inputs will happen more often, if someone has leverage on many votes.

I think that issue could eventually be mitigated, if you would add a rule to the choice of people who are allowed to vote at all with graph theory algorithms. It should be impossible, that more than a few percent of voting identities are from the same invite cluster.  If too many identities from your cluster did vote on that topic, you get a message to "try again later" and that you are blocked from voting for the moment.

The cheaper alternative is for sure a randomized right to vote given only to a small part of the network, but in the long run that seems like a waste of possibility?

The security of honest and unique voting is really important for the unique selling point of idena against other oracles imo.

Thank you for your work!

**Comment by ubiubi18** [comment]
and for sure the same mechanism could also be applied to the right to issue in invites at all!

**Comment by midenaio** [comment]
An attacker with many controlled accounts may adapt the topology of their connections in such a way that an open graph analysis algorithm would not be able to detect collusion. Mining delegation will be used to identify clusters. Feel free to reopen the issue if you have any more ideas on how this can be improved.
