### ISSUE TITLE
MemberH - Win built-in node goes offline

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#530]
Hello, here are all [logs.zip](https://github.com/idena-network/idena-go/files/5089554/logs.zip) from one member.

He is on Win10, running built in node, he comments:
"The node in the last built in client seems a tad unstable guys. I had node failure 2 times in a scope of just a few hours (maybe 6 hours), resulting in mining penalty. Just thought you should know.
Did not download it, but updated via the button in the client. The first node crash was when using wifi, so I thought maybe that was the cause of it, but then it happened again when using rock solid ethernet connection too.
No, not using vps, on my home computer, not had any problems like that for months."

**Comment by ridenaio** [comment]
Hi, the issue is too old, please feel free to create a new one if the problem still exists.
