### ISSUE TITLE
Changelog and update instructions

### ISSUE THREAD

**Issue by ivanovv** [idena-network/idena-go#547]
It would be awesome if the project had a proper changelog and update instructions.

Is it safe to asume that for now changing the node-go executable is the only step needed?

**Comment by ivanovv** [comment]
Quick Q - does deleteing ipfs folder means new key generation?
I did `rm -rf datadir/ipfs` and I see this in the log:

```
Sep 23 22:41:40 idena-1 idena[59489]: INFO [09-23|22:41:40.268] Idena node is starting                   version=0.22.0
Sep 23 22:41:40 idena-1 idena[59489]: ERROR[09-23|22:41:40.392] Failed to persist swarm file: open /home/idena/datadir/ipfs/swarm.key: no such file or directory
Sep 23 22:41:40 idena-1 idena[59489]: generating 2048-bit RSA keypair...done <--- ???
Sep 23 22:41:40 idena-1 idena[59489]: peer identity: Qmejg9e6JbAf11JiPgZfvJQojQDeMvmjLx4W6jByAtNk2Y
Sep 23 22:41:46 idena-1 idena[59489]: INFO [09-23|22:41:46.673] Ipfs initialized                         peerId=Qmejg9e6JbAf11JiPGZfvJQojQDemvmJLx4W6jByAtNk2y
```

**Comment by rioda-org** [comment]
Idena node spins up ipfs node, for idena purposes you have private key for your idena address which is stored in datadir/keystore/nodekey file.
Other than that in datadir/ipfs, for purposes of connecting to idena ipfs network, node generates its keys for ipfs identification on the network. By deleting ipfs folder, node regenerates new keys to communicate on network and it's not big deal.

It is big deal if you get your node into list of bootstrap nodes that start the network, in that case, it would be neccesary to keep your ifps keys so you keep your node ipfs identifications.

But your idena private key(nodekey) stays intact.
