### ISSUE TITLE
Need somehow to limit cpu usage by default

### ISSUE THREAD

**Issue by Toni-d-e-v** [idena-network/idena-go#549]
Digital Ocean is shut downing vps with really high usage just wanna say.

**Comment by RealMahmoud** [comment]
Then you should get a better cpu

**Comment by Toni-d-e-v** [comment]
> Then you should get a better cpu

Nah I'm saying it because of vps

**Comment by ridenaio** [comment]
Hi! You can limit CPU usage by using docker containers. More information you can read [here](https://docs.docker.com/config/containers/resource_constraints/#cpu). 

Download [Dockerfile](https://github.com/idena-network/idena-go/blob/master/Dockerfile) and follow instructions on the top of it.
