### ISSUE TITLE
Deprecating code as best practice to avoid regression errors

### ISSUE THREAD

**Issue by menxit** [idena-network/idena-go#572]
[This commit](https://github.com/idena-network/idena-go/commit/7a11ee171f0c1ce6d01534517841e47d66fe33fc#diff-b522c4590b5a0fd8b3a8b3ceab08b90aL210) introduced the renaming of an endpoint from `bcn_feePerByte` to `bcn_feePerGas`. However idena-js and [idena-pocket](http://pocket.idena.dev/) relies on this endpoint and the endpoint rename caused a temporary outage of our web wallet. As development best practice to avoid regression errors, I suggest not change public interface without a deprecating phase.

**Comment by ridenaio** [comment]
Hi, sorry for the inconvenience. We did not pay attention to this problem during the release. Hope not to have such problems in the future.
