### ISSUE TITLE
panic for idena-go --version 

### ISSUE THREAD

**Issue by viteshan** [idena-network/idena-go#609]
macos info: High Sierra  10.13.6   Macbook Air

./idena-go --version
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/fanglige/Library/Application Support/Idena/node/./idena-go
  Expected in: flat namespace

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/fanglige/Library/Application Support/Idena/node/./idena-go
  Expected in: flat namespace

SIGABRT: abort
PC=0x8a7e256 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5088720, 0xc0000c9eb0, 0x56514cf)
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/cgocall.go:133 +0x5b fp=0xc0000c9e80 sp=0xc0000c9e48 pc=0x400551b
github.com/idena-network/idena-go/crypto/secp256k1._Cfunc_secp256k1_context_create_sign_verify(0x0)
	_cgo_gotypes.go:155 +0x4a fp=0xc0000c9eb0 sp=0xc0000c9e80 pc=0x429839a
github.com/idena-network/idena-go/crypto/secp256k1.init.1()
	/Users/runner/work/idena-go/idena-go/crypto/secp256k1/secp256.go:37 +0x22 fp=0xc0000c9ec8 sp=0xc0000c9eb0 pc=0x429af42
runtime.doInit(0x67e2f40)
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:5480 +0x8a fp=0xc0000c9ef8 sp=0xc0000c9ec8 pc=0x404644a
runtime.doInit(0x67eefe0)
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0000c9f28 sp=0xc0000c9ef8 pc=0x4046417
runtime.doInit(0x67ec2a0)
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0000c9f58 sp=0xc0000c9f28 pc=0x4046417
runtime.doInit(0x67e76e0)
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:5475 +0x57 fp=0xc0000c9f88 sp=0xc0000c9f58 pc=0x4046417
runtime.main()
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/proc.go:190 +0x1b6 fp=0xc0000c9fe0 sp=0xc0000c9f88 pc=0x40397c6
runtime.goexit()
	/Users/runner/hostedtoolcache/go/1.14.13/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0000c9fe8 sp=0xc0000c9fe0 pc=0x4067de1

rax    0x2000209
rbx    0x4
rcx    0x7ffeefbfe7b8
rdx    0x7ffeefbfec30
rdi    0x6
rsi    0x4
rbp    0x7ffeefbfe810
rsp    0x7ffeefbfe7b8
r8     0x7ffeefbfe830
r9     0x0
r10    0x77
r11    0x246
r12    0x77
r13    0x7ffeefbfec30
r14    0x6
r15    0x0
rip    0x8a7e256
rflags 0x246
cs     0x7
fs     0x0
gs     0x0

**Comment by ridenaio** [comment]
Hi, unfortunately, we do not support versions older than macos 10.15. If you want to run idena on macos 10.13 you need to build it on your own.
