### ISSUE TITLE
Hatter - Node keeps chrashing on my windows 10

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#612]
Hatter:
My node keeps chrashing on my windows 10 system, dont think its very stable. I do not run a vps, just regular windows.
Node 0.24.0
Client 0.19.2
Windows 10 Pro 20H2
Dosn't even last an hour before it chrashes.
5-4670K running at 4ghz. Ethernet cable. No net time installed, but very recent manually synchronized to windows time server.

All logs are here
[output.zip](https://github.com/idena-network/idena-go/files/5775512/output.zip)

**Comment by ridenaio** [comment]
Hi, this panic was in `github.com/klauspost/compress` package. Since that, we have already upgraded this package several times. Please, let us know if the problem still exists.

**Comment by rioda-org** [comment]
Hatter is nowhere to be found, let's close it for now
