### ISSUE TITLE
Darko - full hdd on vps after 6 days

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#613]
Hello, finaly i got one user with this case, he has sent me logs

Digital ocean
hdd full after 6 days
2cpu 2 GB, 25gb hdd 15$/month
using idena manager

[f609c7401cd2b5ac.zip](https://github.com/idena-network/idena-go/files/5789652/f609c7401cd2b5ac.zip)

**Comment by ridenaio** [comment]
Hi, we a familiar with this problem. As we know, it appears from IPFS badger datastore. We hope that this problem will be solved when IPFS moves to badger 2.0.
