### ISSUE TITLE
score dropped to less than 100% despite the fact that all short validation sessions were 100% completed

### ISSUE THREAD

**Issue by serdrdoor** [idena-network/idena-go#621]
![image](https://user-images.githubusercontent.com/11815105/105043508-ac66ef80-5a76-11eb-820a-8aa9e205106d.png)

Why after the 61st epoch my score dropped to less than 100% despite the fact that all short validation  sessions were 100% completed
And also I received only 1 invite instead of 2.

see this address:
https://scan.idena.io/address/0xd102b1ed8b90b282ddd2a3100d67bcfaf7843c3f

**Comment by serdrdoor** [comment]
strange, but at epoch 62 at 100% I received 2 invites again...

**Comment by ridenaio** [comment]
Hi, there was a temporary bug with precision while we were moving to the new score calculation system.
