### ISSUE TITLE
Compiling Fails: "cgo: exec /missing-cc: fork/exec /missing-cc: no such file or directory"

### ISSUE THREAD

**Issue by reowens** [idena-network/idena-go#626]
Hi all-
I receive the following when compliling for arm64 on a Raspberry Pi4:

```
ubuntu@ubuntu:~/go/src/idena-go-0.24.2$ go build -ldflags "-X main.version=0.24.2"
# GitHub.com/idena-network/idena-go/crypto/secp256k1
cgo: exec /missing-cc: fork/exec /missing-cc: no such file or directory
```
I have the latest version of go1.15.7 and have also tried compiling with go1.14.14. Any direction would be appreciated, have tried everything.

Thanks

**Comment by reowens** [comment]
I've now tried using xgo and receive this:
`
standard_init_linux.go:211: exec user process caused "exec format error"
`
For the life of me, I don't understand why this is so hard to compile?

**Comment by ridenaio** [comment]
Hi, please take a look at this issue #643
