### ISSUE TITLE
Built-in node keeps failing

### ISSUE THREAD

**Issue by muniatu** [idena-network/idena-go#640]
**Describe the bug**
The built-in node syncs as usual but disconnects shortly after sync. I tried to validate through the browser and got suspended as well...

**Module**
- Settings

**Expected behavior**
The node doesn't disconnect.

**Identity context**
- Suspended
- 0x8d654de829260396971609f0956db8eb6c732907
- https://scan.idena.io/identity/0x8d654de829260396971609f0956db8eb6c732907/epoch/64/validation

**Idena Client logs**
[error.log](https://github.com/idena-network/idena-desktop/files/6023018/error.log)

**Screenshots / Screencasts**
<img width="739" alt="Screenshot 2021-02-22 at 16 27 25" src="https://user-images.githubusercontent.com/4389787/108729499-dfdfe280-752a-11eb-8eeb-2f18a5991cf3.png">

**Environment:**
 - macOS 10.14.6
 - built-in
 - Client version 0.20.0
 - Node version 0.24.2

**Comment by sidenaio** [comment]
Fixed in #641
