### ISSUE TITLE
Synchronization Failed

### ISSUE THREAD

**Issue by ungitted** [idena-network/idena-go#643]
Raspberry Pi 4 - 2GB ram- no desktop install
idena-go compiled without problems, 10 hours of synchronization failed at the last process batch, errors:

- invalid block roots
- invalid max fee
- peer has been banned

idena 0.24.1 / golang 1.15
[stdout.log](https://github.com/idena-network/idena-go/files/6071678/stdout.log)

installed from scratch idena 0.24.1 / golang 1.15 , 10 hours synchronization failed again in last process batch
[stdout2.log](https://github.com/idena-network/idena-go/files/6071711/stdout2.log)

installed from scratch idena 0.24.2 / golang 1.16 , downloaded idenachain.db for fast sync, failed in last process batch
[stdout3.log](https://github.com/idena-network/idena-go/files/6071727/stdout3.log)

idena 0.24.3 / golang 1.16 , downloaded idenachain.db for fast sync, failed in last process batch
[stdout4.log](https://github.com/idena-network/idena-go/files/6071737/stdout4.log)

any ideas?

**Comment by sidenaio** [comment]
Hi, what OS do you use?

**Comment by ungitted** [comment]
Ubuntu Server 20.04
using this tutorial https://idena.site/faq/idena-node-on-raspbery-pi-4

**Comment by sidenaio** [comment]
I think the instruction has mistake. Idena node correctly works only on 64-bit OS

**Comment by ungitted** [comment]
I was almost sure I had tried it on both 32 and 64 bits, but to be sure I have installed it again in 64 bits and now it is working correctly, it has synced! Thanks a lot
