### ISSUE TITLE
My sharing node db is crashing: "too many open files"

### ISSUE THREAD

**Issue by ltraveler** [idena-network/idena-go#655]
I couldn't start my sharing node. I am always getting an error after sometimes of correct work:
`ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: netlinkrib: too many open files"}`
`failed to load db prefix: failed to get value: open datadir/idenachain.db/000041.ldb: too many open files.
I am using the latest version of the node, which is 0.24.3
`

**Comment by ridenaio** [comment]
Hi! Is the problem still exists on v0.25.0 ?

**Comment by ltraveler** [comment]
Yes.

**Comment by ltraveler** [comment]
`Idena node is starting                   version=0.25.0
ERROR        basichost        failed to resolve local interface addresses {"error": "route ip+net: netlinkrib: too many open files"}
failed to load db prefix: failed to get value: open datadir/idenachain.db/012796.ldb: too many open files
`

**Comment by sidenaio** [comment]
What OS do you use? Please share your full node logs.

**Comment by ltraveler** [comment]
`lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
`
[https://gist.github.com/ltraveler/8c39dbcc88a3515905b21935160184bc](url)

**Comment by ltraveler** [comment]
I found a temporary solution by using 
`ulimit -n 524288`
before the value was 1024

**Comment by sidenaio** [comment]
On your system node can't increase fd limit to 65535 and uses 4096. It's not enough for stable working.
`Set new fd limit                         value=4096`

 I would recommend you to increase limits manually. How to permanently set up ulimit you can find [here](https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a).

**Comment by ltraveler** [comment]
Probably it is because the node run as a regular user.
I think it would be nice to add this part to the README.md

**Comment by ltraveler** [comment]
The node starts to crash again with the same error. I have upgraded `/etc/security/limits.conf` as it is described in the instruction above. But the node is still crashing with the same error.

**Comment by ridenaio** [comment]
What is your current limit? You need to increase it to 65535.

**Comment by ltraveler** [comment]
I have tried even more up to 524288.
Then I have updated my Ubuntu to 20.04 looks like it solved the problem.
