### ISSUE TITLE
 preventing node from accepting delegate suspended identity

### ISSUE THREAD

**Issue by idena-Egyptian-Pharoh** [idena-network/idena-go#660]
![image](https://user-images.githubusercontent.com/75703728/112730948-14392b00-8f3d-11eb-830b-7ad88dac7835.png)

**Comment by nikbitnode** [comment]
delegation also works for a new account that has not passed more than one test.  and as a result, there is no way to enable mining, and there is no way to remove delegation.

**Comment by sidenaio** [comment]
Hi, you can delegate to any node, even if it is not validated. You should wait for 1-50 blocks to apply delegation status on delegator. When delegation status applied, you are able to switch on mining on the main node. I recommend to delegate to not validated node. If pool participates in validation and fails it, pool will be removed from online nodes, and you will need to enable mining manually.
