### ISSUE TITLE
Executing node from different locations

### ISSUE THREAD

**Issue by pradoh97** [idena-network/idena-go#703]
### Brief introduction:
 - The user running the node is **idena** (running without sudo)
 - OS: Ubuntu server 20.04
 - idena node script is located in _/home/idena/_ which I will refeer to as **node location**
 - The file name is _idena-node-linux-0.26.2_
 - from now on I will refer to executing _/home/idena/idena-node-linux-0.26.2_ as **running the node**.

### Scenario/Steps to reproduce:
 - running from within the same path as the **node location** produces, inside that location, datadir folder and all the subsequent ones.
 - **running the node** from a different path, lets say _/home/_ produces, inside that location, datadir folder and all the subsequent ones.

Thus, with this scenario, **running the node** will create its directory structure (and start synching from the beginning) based on the path from where the user called it.

Would not it make more sense to look up/create the directory structure (and verify/start synching) based on the **node location**?

Edit: the [issue 664](https://github.com/idena-network/idena-go/issues/664) is related to this, since having a new directory structure means having (if not passed as an argument when running the node) a new api key and keystore.

**Comment by ridenaio** [comment]
Hi!

You can specify your own datadir:
- using CLI parameter `--datadir=/home/a/b/c`
- using [JSON configuration file](https://github.com/idena-network/idena-go#json-config)

**Comment by pradoh97** [comment]
> Hi!
> 
> You can specify your own datadir:
> 
>     * using CLI parameter `--datadir=/home/a/b/c`
> 
>     * using [JSON configuration file](https://github.com/idena-network/idena-go#json-config)

Thanks, I guess it's just me who expected the behavior as 

> to look up/create the directory structure (and verify/start synching) based on the node location?
