### ISSUE TITLE
Validation problem

### ISSUE THREAD

**Issue by an-trader** [idena-network/idena-go#747]
Good day!
I bring to your attention that there is a bug in the system.
I tell you by my example:
1. During a short session, the flips were loaded for a long time, but they loaded.
2. During a long session, only seven flips were loaded (there were nineteen in total). The rest of the flips, initially, did not even have keywords, but later the keywords appeared.
On the flips themselves it was written: "Skip this flip."
At the time of sending the responses, it was indicated: "You are sending seven flips out of seven", but when they appeared.

**Server characteristics during validation:**
Hetzner.Cloud (Helsinki)
CPU - 2 cores (Intel ® Xeon ® Gold)
RAM - 4 GB
ROM - 20 GB NVMe
OS Ubuntu 20.04
SWAP - 1 GB
1 Gbit/sec

**Idea desktop (client) is installed on a local PC:**
Windows 10 Pro (licensed)
Intel i7
ROM - 4 GB
200 Mbit / sec
No extra programs are running (I turn everything off before validation)
**Suspended**
0xed74563895b457d4b27e05b8fc62b86fde0fabd1

**logs below**

![Screenshot_1](https://user-images.githubusercontent.com/87753268/126901583-17f386fb-424b-4c94-b0c4-4b50d56e7853.png)

![Screenshot_2](https://user-images.githubusercontent.com/87753268/126901594-a0d6cc8b-cdd6-4a66-b58d-ce76a92fd88a.png)

![Screenshot_3](https://user-images.githubusercontent.com/87753268/126901598-632b499a-bea9-4b94-9813-0d3d66fd4a85.png)

![Screenshot_4](https://user-images.githubusercontent.com/87753268/126901628-a49faf7d-1ea5-4525-bd04-417c408ab39a.png)

![Screenshot_5](https://user-images.githubusercontent.com/87753268/126901639-13240084-4779-4729-aca2-71a39a0e4671.png)

![Screenshot_6](https://user-images.githubusercontent.com/87753268/126901640-35246775-6f7a-42d3-bc64-40ac71d3e824.png)

![Screenshot_7](https://user-images.githubusercontent.com/87753268/126901642-4e1cc6a7-1b4a-417e-b350-c34407a79ead.png)

![Screenshot_8](https://user-images.githubusercontent.com/87753268/126901643-f27550ab-a39d-4c79-8c62-d2bf3837cb37.png)

![Screenshot_9](https://user-images.githubusercontent.com/87753268/126901649-9c9bff54-bd5c-4871-8941-5533cab275b9.png)

![Screenshot_10](https://user-images.githubusercontent.com/87753268/126901652-cc0bbfbb-c5ec-4301-a3d8-608293daa1a9.png)

![Server](https://user-images.githubusercontent.com/87753268/126901653-2bf11af9-60aa-4ef4-911f-80cd05b1d248.jpg)

![config json](https://user-images.githubusercontent.com/87753268/126901676-605a4dcc-4435-4a67-a06f-308f5713bbf1.jpg)

![idena service](https://user-images.githubusercontent.com/87753268/126901675-fdb2d1ab-4d16-436a-8a2a-318a1290a08e.jpg)

![local PC](https://user-images.githubusercontent.com/87753268/126901678-089a48b3-d803-4a48-a498-58d510ba2843.jpg)

![Internet Speed localPC](https://user-images.githubusercontent.com/87753268/126901681-0386d800-ceb1-4649-aee1-c98774f72fa9.png)

**Files with logs could not be attached - you can download them here**
https://disk.yandex.ru/d/aaVR5Ab649mH-Q

**Comment by an-trader** [comment]
I didn't finish writing it (accidentally):
At the time of sending the responses, it was stated: "You are sending seven flips out of seven", but the results showed seven flips out of seventeen

**Comment by sidenaio** [comment]
Do you have another client logs? In attached logs you ran client in 13:38, 8 min after validation starting.

![image](https://user-images.githubusercontent.com/50700001/128048915-0ce17e1a-cebd-44f4-a627-ff27dff9de77.png)

**Comment by an-trader** [comment]
**Very strange!**
When the images did not load during a long session, I ran to another PC (in another room), started the client and connected to the same remote node, but validation did not start there. I went back to the first PC and reconnected with the PuTTY console, but the images did not load. I switched to checking keywords, they were not loaded immediately. When sending the responses, it was indicated that I am sending seven flivs out of seven. At all stages of validation, it was written: Skip this flip.

Here are the logs from the second PC. From it I tried to connect to a long session, when the first PC did not load pictures.
Maybe it will help to identify the cause

https://disk.yandex.ru/d/BqJqTKHOT25ilQ

**Comment by sidenaio** [comment]
![image](https://user-images.githubusercontent.com/50700001/128321811-03752c3f-d67f-4909-b4fd-18d78e25417e.png)
You've attached the same log file as first.

**Comment by an-trader** [comment]
Obviously, I've been working hard and I'm tired. Accidentally added the same file with logs.
Now I attach all the logs:
https://disk.yandex.ru/d/gF5WFHWhvnurcQ

**Comment by sidenaio** [comment]
According to logs your client lost connection to node in long session.  We'll change logic how to client finalizes flips.

**Comment by an-trader** [comment]
In what update should we expect changes in the logic?

**Comment by sidenaio** [comment]
It's [released](https://github.com/idena-network/idena-desktop/releases/tag/v0.27.0).
