### ISSUE TITLE
Delegatee received full validation reward

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#752]
This delegatee acording to balance update tab as seen on explorer, received validation reward to both main and stake in non 80/20 ratio.
https://scan.idena.io/address/0x50e92C08E75A648eB9cA55db6A18715Db42Bf811#history

![image](https://user-images.githubusercontent.com/37978870/127555425-cb0119a8-dd20-43d6-84cf-1f800a61877a.png)

Wasn't his 80% of unlocked part validation reward supposed to go to pool address?

**Comment by idena-Egyptian-Pharoh** [comment]
weird ...

**Comment by hlolve** [comment]
Is possible different 80/20 if that ID at that time was pool owner and validating, and other ID delegating to the pool is still newbie at that moment, because only 20% of newbie rewards go to pool

**Comment by rioda-org** [comment]
Oh yes, great obeservation, that identity was indeed pool itself before joining other pool. But for his identity to join pool, firstly he must not be pool himself anymore and his connections to all his delegatees must be severed before he can join pool as a regular identity. So there is something wierd going on here or I don't understand pool/delegation mechanics fully.

**Comment by hlolve** [comment]
I think this address https://scan.idena.io/address/0x905C90d56BeCF3C17D8eBABC9C8B1426FA68201D is the answer. This ID was still in the pool when the owner was not anymore a pool. The pool owner stopped the mining and went to other pool but this ID was still in the killed pool in some way. I don't know if pool owner needs all their IDs  undelegated, before stop mining and go to other pool.

**Comment by hlolve** [comment]
At validation time the ID was delegated, but this ID https://scan.idena.io/identity/0x905C90d56BeCF3C17D8eBABC9C8B1426FA68201D could not be moved out of pool because was suspended in that epoch. For that reason maybe the ex pool owner was considered still pool and rewards not went to new pool.

**Comment by hlolve** [comment]
Validation rewards of https://scan.idena.io/address/0x905C90d56BeCF3C17D8eBABC9C8B1426FA68201D#history went to pool, but what pool ?

**Comment by sidenaio** [comment]
Fixed in [0.27.0](https://github.com/idena-network/idena-go/releases/tag/v0.27.0)
