### ISSUE TITLE
Error when I try to terminate a oracle vote

### ISSUE THREAD

**Issue by redDwarf03** [idena-network/idena-go#789]
hello. i tried to use the oraclevoting feature last week. (https://scan.idena.io/contract/0x6d7e44ac220abe6b254dc6a984f2582911546ca1) . The vote is now over but it remains "pending extension". 
So, i try to terminate with rpc (rpc.Idena.io) command but i obtain:
´´´
{
  "method": "contract_terminate",
  "params": [
    {
      "from": "0x72563CB949bd0167ACFFf47b5865fe30e1960e70",
      "contract": "0x6d7e44ac220abe6b254dc6a984f2582911546ca1"
    }
  ],
  "id": 8,
  "key": "xxxxx"
}
Something went wrong :(
´´´

my node (v 0.26.7) said
´´´
ERROR[08-28|14:21:00.716] goroutine 610787 [running]:
github.com/idena-network/idena-go/rpc.(*Server).serveRequest.func1(0xc00277ea00, 0x43db1d8, 0xc0135ddc20)
        D:/a/idena-go/idena-go/rpc/server.go:133 +0x12f
panic(0x3c8bc80, 0xc0194f22a0)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/runtime/panic.go:965 +0x1c7
github.com/cosmos/iavl.(*nodeDB).GetNode(0xc001dfc780, 0xc009375260, 0x20, 0x20, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/nodedb.go:91 +0x6f7
github.com/cosmos/iavl.(*Node).getLeftNode(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:423
github.com/cosmos/iavl.(*Node).get(0xc009414320, 0xc00936a888, 0xc01b047518, 0x15, 0x18, 0xc01b047518, 0x1, 0xc00a143c00, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/node.go:173 +0x225
github.com/cosmos/iavl.(*ImmutableTree).Get(0xc00936a888, 0xc01b047518, 0x15, 0x18, 0x15, 0x18, 0x1, 0x18)
        C:/Users/runneradmin/go/pkg/mod/github.com/idena-network/iavl@v0.12.3-0.20210604085842-854e73deab29/immutable_tree.go:153 +0x65
github.com/idena-network/idena-go/core/state.(*MutableTree).Get(0xc005225420, 0xc01b047518, 0x15, 0x18, 0x0, 0x0, 0x0, 0x0)
        D:/a/idena-go/idena-go/core/state/tree.go:116 +0xbb
github.com/idena-network/idena-go/core/state.(*StateDB).getStateAccount(0xc004d7c6e0, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x98000000700e96e1, 0x0)
        D:/a/idena-go/idena-go/core/state/statedb.go:646 +0x217
github.com/idena-network/idena-go/core/state.(*StateDB).GetOrNewAccountObject(0xc004d7c6e0, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x700e96e1, 0x0)
        D:/a/idena-go/idena-go/core/state/statedb.go:832 +0x46
github.com/idena-network/idena-go/core/state.(*NonceCache).getAccount(0xc0045d62a0, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x49700e96e1, 0x1)
        D:/a/idena-go/idena-go/core/state/nonce_cache.go:76 +0x38c
github.com/idena-network/idena-go/core/state.(*NonceCache).GetNonce(0xc0045d62a0, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x49700e96e1, 0xc000000000)
        D:/a/idena-go/idena-go/core/state/nonce_cache.go:38 +0x96
github.com/idena-network/idena-go/blockchain.BuildTx(0xc013f4f440, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x700e96e1, 0xc0135ddcd4, 0x11, 0xc0001264e0, 0xc000000001, 0x0, 0x0, ...)
        D:/a/idena-go/idena-go/blockchain/helpers.go:35 +0x1dd
github.com/idena-network/idena-go/api.(*BaseApi).getTx(0xc004bc9320, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x700e96e1, 0xc0135ddcd4, 0x1670011, 0xc0001264e0, 0x1, 0x0, 0x0, ...)
        D:/a/idena-go/idena-go/api/base_api.go:65 +0x167
github.com/idena-network/idena-go/api.(*BaseApi).getSignedTx(0xc004bc9320, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0x700e96e1, 0xc0135ddcd4, 0x11, 0xc0001264e0, 0x1, 0x0, 0xc000000000, ...)
        D:/a/idena-go/idena-go/api/base_api.go:79 +0x105
github.com/idena-network/idena-go/api.(*ContractApi).buildTerminateContractTx(0xc00309b800, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0xac447e6d700e96e1, 0xa9c64d256bbe0a22, 0xa16c54112958f284, 0x0, 0x0, 0x0, 0x0, ...)
        D:/a/idena-go/idena-go/api/contract_api.go:235 +0x285
github.com/idena-network/idena-go/api.(*ContractApi).Terminate(0xc00309b800, 0x43c7ba0, 0xc010839840, 0x6701bd49b93c5672, 0x30fe65587bf4ffac, 0xac447e6d700e96e1, 0xa9c64d256bbe0a22, 0xa16c54112958f284, 0x0, 0x0, ...)
        D:/a/idena-go/idena-go/api/contract_api.go:335 +0x7a
reflect.Value.call(0xc002f48300, 0xc004af9b58, 0x13, 0x3f90add, 0x4, 0xc01392c1e0, 0x3, 0x4, 0xc01392c210, 0xc016a80990, ...)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/reflect/value.go:476 +0x907
reflect.Value.Call(0xc002f48300, 0xc004af9b58, 0x13, 0xc01392c1e0, 0x3, 0x4, 0x2, 0x4, 0xc016a80978)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/reflect/value.go:337 +0xc5
github.com/idena-network/idena-go/rpc.(*Server).handle(0xc00277ea00, 0x43c7ba0, 0xc010839840, 0x43db1d8, 0xc0135ddc20, 0xc01392c120, 0xc01392c090, 0x0, 0x3cfbf40)

D:/a/idena-go/idena-go/rpc/server.go:310 +0x6b1
github.com/idena-network/idena-go/rpc.(*Server).exec(0xc00277ea00, 0x43c7ba0, 0xc010839840, 0x43db1d8, 0xc0135ddc20, 0xc01392c120)
        D:/a/idena-go/idena-go/rpc/server.go:331 +0x1de
github.com/idena-network/idena-go/rpc.(*Server).serveRequest(0xc00277ea00, 0x43c7c48, 0xc01e0836e0, 0x43db1d8, 0xc0135ddc20, 0xc0194f2201, 0x1, 0x0, 0x0)
        D:/a/idena-go/idena-go/rpc/server.go:193 +0x445
github.com/idena-network/idena-go/rpc.(*Server).ServeSingleRequest(...)
        D:/a/idena-go/idena-go/rpc/server.go:224
github.com/idena-network/idena-go/rpc.(*Server).ServeHTTP(0xc00277ea00, 0x43c0d28, 0xc003344380, 0xc0185b7900)
        D:/a/idena-go/idena-go/rpc/http.go:253 +0x7c5
github.com/rs/cors.(*Cors).Handler.func1(0x43c0d28, 0xc003344380, 0xc0185b7900)
        C:/Users/runneradmin/go/pkg/mod/github.com/rs/cors@v1.8.0/cors.go:219 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000fbed40, 0x43c0d28, 0xc003344380, 0xc0185b7900)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/net/http/server.go:2049 +0x4b
github.com/idena-network/idena-go/rpc.(*virtualHostHandler).ServeHTTP(0xc004aeb7d0, 0x43c0d28, 0xc003344380, 0xc0185b7900)
        D:/a/idena-go/idena-go/rpc/http.go:312 +0x211
net/http.serverHandler.ServeHTTP(0xc00022ad20, 0x43c0d28, 0xc003344380, 0xc0185b7900)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/net/http/server.go:2867 +0xaa
net/http.(*conn).serve(0xc003e8d220, 0x43c7c48, 0xc008797e40)
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        C:/hostedtoolcache/windows/go/1.16.6/x64/src/net/http/server.go:2993 +0x3b8
´´´

any idea about this error

**Comment by redDwarf03** [comment]
i retested today.. perhaps i had a synchronized issue yesterday...
now i have this message
````{
  "jsonrpc": "2.0",
  "id": 4,
  "error": {
    "code": -32000,
    "message": "invalid payload"
  }
}
````

**Comment by redDwarf03** [comment]
i tried this... 
```
{
  "method": "contract_estimateTerminate",
  "params": [
    {
      "contract": "0x6d7e44ac220abe6b254dc6a984f2582911546ca1",
      "args": [
        {
          "index": 0,
          "format": "hex",
          "value": "0x72563CB949bd0167ACFFf47b5865fe30e1960e70"
        }
      ]
    }
  ],
  "id": 7,
  "key": "xxxxxxx"
}
{
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "contract": "0x6d7e44ac220abe6b254dc6a984f2582911546ca1",
    "method": "terminate",
    "success": false,
    "gasUsed": 270,
    "txHash": "0x5ad85d8b00a128ee33a59bbf02c04742a631aa3a06eeb3c94cc0e415dbcd76f3",
    "error": "voting can not be terminated",
    "gasCost": "0.000316381532688",
    "txFee": "0.00152331849072"
  }
}
```

**Comment by midenaio** [comment]
The voting has `Open` status. It can not be terminated yet. You need to wait for the quorum to be reached or for three consecutive prolongings with low voting activity (the number of votes grows by less than 10%).

**Comment by redDwarf03** [comment]
Ah ok. Thx
