### ISSUE TITLE
Desktop app switched to long session ahead of time?

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#870]
Hello, one member (Haris TG) had problem with validation, here are his logs.
Desktop app, built in node
[logs.zip](https://github.com/idena-network/idena-go/files/7574796/logs.zip)

**Comment by rioda-org** [comment]
I have reopened this issue as I can't confirm (don't know how to read logs) when member clicked on flips. Don't know if his time for short session just passed and he did not notice or it was some bug.

He told me he was doing short session, solved 3 flips and app switched him to long session all of a sudden.
He is using Windows 10, has NetTime installed, as I mentioned before, Desktop App, built in node.
His validation
https://scan.idena.io/identity/0x11b017A259775be117f1e2Df42c45b3F7A6d0420/epoch/78/validation

**Comment by hlolve** [comment]
> I have reopened this issue as I can't confirm (don't know how to read logs) when member clicked on flips. Don't know if his time for short session just passed and he did not notice or it was some bug.
> 
> He told me he was doing short session, solved 3 flips and app switched him to long session all of a sudden. He is using Windows 10, has NetTime installed, as I mentioned before, Desktop App, built in node. His validation https://scan.idena.io/identity/0x11b017A259775be117f1e2Df42c45b3F7A6d0420/epoch/78/validation



The ID answered 4 flips ( 3 Ok - 1 wrong ) and sent short answers at 13:31:49

INFO [11-20|13:31:49.395] Broadcast ceremony tx                    type=5 hash=0xd47446efab44369eee661f61634dcb68de58a6dcf516331f05019ac3f8f92c1a
