### ISSUE TITLE
Private Network?

### ISSUE THREAD

**Issue by Toni-d-e-v** [idena-network/idena-go#874]
I made config with different ports and I would like to create private idena network but I get error that genesis block is not found how would I create one? Thanks 
![image](https://user-images.githubusercontent.com/62844491/143307669-4a683e68-c752-4c77-aa4e-6ace985bfe8c.png)

**Comment by Toni-d-e-v** [comment]
fixed it just deleted datadir

**Comment by Toni-d-e-v** [comment]
How would I get first invite for first validation?

**Comment by Toni-d-e-v** [comment]
created one using send invite with rpc :)

**Comment by Toni-d-e-v** [comment]
I got to the point where 1st validation starts but client does not show flips so no flips are summited do I need to submit rand flips via rpc? 
last block ```
    "coinbase": "0x0000000000000000000000000000000000000000",
    "hash": "0x377109986707061a4b35b1c29587ca67306f2d39f64d9645a9403f419ecee911",
    "parentHash": "0x3520f7d321714e76bb774eacc6320dcd5aae83953052045fc38ae75d34b5da10",
    "height": 69,
    "timestamp": 1637790007,
    "root": "0x1fa7afeca33aaa9b432f76b764a43938e7551715e874d379afd0614a8ea4319d",
    "identityRoot": "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "ipfsCid": null,
    "transactions": null,
    "flags": null,
    "isEmpty": true,
    "offlineAddress": null
```

**Comment by aidenaio** [comment]
yes you should submit flip to be able to validate at least yourself
