### ISSUE TITLE
No key words loaded when validating or creating flips

### ISSUE THREAD

**Issue by DyuldinKS** [idena-network/idena-go#875]
Hi!
I've first encountered this error during the last validation (epoch 78) - no key words were loaded for any flip, the field for words was just empty. Now I see the same problem when trying to create flips:

![image](https://user-images.githubusercontent.com/17742916/143134702-31424cb4-f5e1-461f-aaa7-d5f768331fd9.png)

**Validation context**
epoch: idena-network/idena-desktop#78
status: Newbie
identity: 0x1df1e66d44c4414a9d927ebbe6ab7663a1bc0686

**Environment:**
OS: macOS 11.3.1 (20E241)
Node mode: both remote (Digital Ocean) and local
Client version: 0.22.3
Node version: 0.28.1

client logs: [idena.log](https://github.com/idena-network/idena-desktop/files/7591365/idena.log)

**Comment by aidenaio** [comment]
moving to the node project

**Comment by sidenaio** [comment]
Hi, @DyuldinKS 
Your client is outdated. Current version is 0.28.1
