### ISSUE TITLE
Stuck at "Idena Node is starting.."

### ISSUE THREAD

**Issue by ligi** [idena-network/idena-go#876]
when opening idena currently I just see:

![image](https://user-images.githubusercontent.com/111600/142756613-520b79ea-8c02-4fca-8b58-c9fe2192ba8b.png)

in the console I see:

```
✓ ~ idena-desktop                                                                                            Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Idena/resources/app-update.yml'
```

in the node log I see:

```
INFO [11-21|09:27:42.880] Idena node is starting version=0.28.1
ERROR[11-21|09:27:42.906] ipfs repo needs migration
```

I was running a VPS for a long time - but for a test wanted to switch to the build-in node - this caused the problem I think. It should recover from this Error I think.

**Comment by sidenaio** [comment]
Please drop ipfs folder from your datadir
