### ISSUE TITLE
No keywords showing on desktop

### ISSUE THREAD

**Issue by Mettodo** [idena-network/idena-go#886]
I could not read any keyword during the validation and I am trying to create new flips but keywords do not appear.
![Selection_034](https://user-images.githubusercontent.com/24914615/145680518-6299d34d-54f5-41f5-a5c9-11a310ecb023.png)
![Selection_035](https://user-images.githubusercontent.com/24914615/145680591-f8c71b60-47e7-4ee2-bdc9-77153e354123.png)
[](url)
I am running client version 0.20.0, node version 0.28.2
Here my client´s log file: 
[Log file.zip](https://github.com/idena-network/idena-go/files/7697222/Log.file.zip)

**Comment by rioda-org** [comment]
That's a very old client version, just update it by installing latest from website and problem will be solved.
