### ISSUE TITLE
Offline penalty

### ISSUE THREAD

**Issue by hlolve** [idena-network/idena-go#915]
Some nodes (not pool) got penalties without been offline, I think they can't be selected in the 1 hour time frame. Each node has a probability of 1/135 (at present) to be selected, and there are 180 blocks in 1 hour. If is not increased the number of validators per block or increased time frame, that can be a problem for not pool nodes ?

**Comment by sidenaio** [comment]
Hi, each round has 4 steps. One step requires 100 identities in the committee. As a result we have 400 / 12000 (current online) ~ 3% probability to be selected as a voter for a block. 33 rounds give us ~100% chance to be selected.

**Comment by hlolve** [comment]
Last seen, is considered for a block issued or a vote for a block issue. For a block issued is needed 100 IDs or 400 IDs ? and 100 IDs or 400 IDs are included as last seen in that  block ?

**Comment by sidenaio** [comment]
Each round ~5 identities propose blocks. 400 identities are needed to confirm a block. So 405 identities are marked as seen.

**Comment by hlolve** [comment]
Thank you
