### ISSUE TITLE
Node getting penalty while being online

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-go#930]
Hello, here is example of a node receiving penalty while being online
https://scan.idena.io/address/0xc34D15574EC0B650cC19ffCF3489A6Ae0b3f25C6#penalty

[output.zip](https://github.com/idena-network/idena-go/files/8128739/output.zip)

**Comment by rioda-org** [comment]
Same thing, new penalty

![image](https://user-images.githubusercontent.com/37978870/157232229-8e715827-9701-4085-afe2-405ecc5b18f2.png)

**Comment by hlolve** [comment]
I have the same problem, and didn't find a solution
https://github.com/idena-network/idena-go/issues/915

**Comment by rioda-org** [comment]
Hmm, yes, it seems that theory tells us one story, but in practice we get this as a real situation.
Is your node on vps or at home pc? My node is at home.
Yesterday I had one new member who just started mining on his own laptop. In 4 hours he got penalty. He had sent me his logs, he was online all the time, also, good number of peers. And he asked me, what could be the problem :)

**Comment by hlolve** [comment]
VPS with 4 vcpu and 4 gb ram, got penalty without went offline, running in default config and in lowpower. Tested also 2 nodes in same vps, one got penalty and the other not, on same period of time. If one is delegated on other didn't get penallty

**Comment by rioda-org** [comment]
Even pool of two is in 100% better position than standalone mining nodes. Not really great situation. I will continue to post my offline penalties just so we are aware of this happening and so we are aware that this could provide funky experience for new people.
